"use strict";
const $=s=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d");
const ui={bs:$("#blue-score"),rs:$("#red-score"),timer:$("#timer"),mapLabel:$("#map-label"),modeStatus:$("#mode-status"),bossHud:$("#boss-hud"),bossFill:$("#boss-health-fill"),bossPhase:$("#boss-phase"),hp:$("#hp-text"),fill:$("#health-fill"),respawn:$("#respawn-text"),skillProgress:$("#skill-progress"),classLabel:$("#class-label"),ability:$("#ability-button"),abilityName:$("#ability-name"),abilityCooldown:$("#ability-cooldown"),start:$("#start-screen"),pause:$("#pause-screen"),settingsScreen:$("#settings-screen"),upgradeScreen:$("#upgrade-screen"),missionScreen:$("#mission-screen"),missionList:$("#mission-list"),achievementList:$("#achievement-list"),missionWallet:$("#mission-coin-balance"),result:$("#result-screen"),title:$("#result-title"),score:$("#result-score"),best:$("#best-time"),wallet:$("#coin-balance"),shopWallet:$("#shop-coin-balance"),resultCoins:$("#result-coins"),shopClassName:$("#shop-class-name"),shopMessage:$("#shop-message"),resultBest:$("#result-best"),statTime:$("#stat-time"),statKills:$("#stat-kills"),statDeaths:$("#stat-deaths"),statShots:$("#stat-shots"),statAccuracy:$("#stat-accuracy"),statDamage:$("#stat-damage"),shakeToggle:$("#shake-toggle"),soundToggle:$("#sound-toggle"),vibrationToggle:$("#vibration-toggle")};
const WORLD={w:1800,h:1100},COLOR={blue:"#3dd8ff",red:"#ff4d76"},keys=new Set(),pointer={x:0,y:0,down:false,seen:false},input={mx:0,my:0,ax:1,ay:0,fire:false};
const CLASSES={assault:{label:"돌격형",ability:"오버드라이브",hp:100,speed:285,rate:.19,damage:22,color:"#42d8ff"},tank:{label:"탱커형",ability:"보호막",hp:160,speed:220,rate:.34,damage:25,color:"#9b8cff"},sniper:{label:"저격형",ability:"관통탄",hp:85,speed:235,rate:.62,damage:52,color:"#ffd45c"}};
const MAPS={
factory:{label:"네온 공장",bg:"#11192d",grid:"#5a82be13",block:"#253151",edge:"#85aeff33",obstacles:[{x:500,y:200,w:115,h:265},{x:500,y:635,w:115,h:265},{x:1185,y:200,w:115,h:265},{x:1185,y:635,w:115,h:265},{x:800,y:70,w:200,h:105},{x:800,y:925,w:200,h:105},{x:820,y:435,w:160,h:230}]},
crossfire:{label:"크로스 광장",bg:"#18142b",grid:"#c278ff16",block:"#3b2851",edge:"#ef9cff3d",obstacles:[{x:610,y:190,w:155,h:155},{x:1035,y:190,w:155,h:155},{x:610,y:755,w:155,h:155},{x:1035,y:755,w:155,h:155},{x:825,y:430,w:150,h:240},{x:390,y:475,w:90,h:150},{x:1320,y:475,w:90,h:150}]},
corridor:{label:"트윈 통로",bg:"#0d2024",grid:"#51ffd416",block:"#1d4748",edge:"#72ffe04a",obstacles:[{x:475,y:105,w:105,h:365},{x:475,y:630,w:105,h:365},{x:850,y:245,w:100,h:610},{x:1220,y:105,w:105,h:365},{x:1220,y:630,w:105,h:365},{x:680,y:60,w:170,h:90},{x:950,y:950,w:170,h:90}]}
};
const BEST_TIME_KEY="neon-clash-best-win-time";
const SETTINGS_KEY="neon-clash-settings";
const PROFILE_KEY="neon-clash-profile-v1";
const MISSIONS=[
{id:"first_hunt",icon:"🎯",title:"첫 사냥",detail:"누적 10킬 달성",stat:"kills",goal:10,reward:40},
{id:"veteran",icon:"🎮",title:"꾸준한 도전자",detail:"경기 5회 완료",stat:"matches",goal:5,reward:60},
{id:"winner",icon:"🏅",title:"승리 행진",detail:"3회 승리",stat:"wins",goal:3,reward:80},
{id:"wave",icon:"🌊",title:"최후의 웨이브",detail:"웨이브 5 도달",stat:"bestWave",goal:5,reward:100},
{id:"boss",icon:"👑",title:"가디언 공략",detail:"보스전 누적 피해 1,000",stat:"bossDamage",goal:1000,reward:120}
];
const PERIOD_MISSIONS={
daily:[{id:"play",icon:"🎮",title:"오늘의 출전",detail:"경기 2회 완료",stat:"matches",goal:2,reward:25},{id:"kills",icon:"🎯",title:"오늘의 사냥",detail:"8킬 달성",stat:"kills",goal:8,reward:35},{id:"damage",icon:"💥",title:"화력 점검",detail:"피해 500 주기",stat:"damage",goal:500,reward:30}],
weekly:[{id:"play",icon:"📅",title:"주간 도전자",detail:"경기 10회 완료",stat:"matches",goal:10,reward:100},{id:"wins",icon:"🏆",title:"승리 수집가",detail:"5회 승리",stat:"wins",goal:5,reward:140},{id:"waves",icon:"🌊",title:"생존 훈련",detail:"웨이브 모드 3회 플레이",stat:"wavePlays",goal:3,reward:120}]
};
const LONG_MISSIONS={
kills:{icon:"🎯",title:"베테랑 헌터",stat:"kills",goals:[10,50,100,250],rewards:[50,100,180,350],unit:"누적 킬"},
wins:{icon:"🏅",title:"아레나 챔피언",stat:"wins",goals:[3,10,25,50],rewards:[60,130,250,450],unit:"누적 승리"},
boss:{icon:"👑",title:"가디언 정복자",stat:"bossWins",goals:[1,3,5,10],rewards:[80,160,260,500],unit:"보스 격파"}
};
const ACHIEVEMENTS=[
{icon:"🚀",title:"첫 출전",detail:"첫 경기를 완료하세요",test:p=>p.stats.matches>=1},
{icon:"🎯",title:"네온 사냥꾼",detail:"누적 25킬을 달성하세요",test:p=>p.stats.kills>=25},
{icon:"🏆",title:"승리의 시작",detail:"첫 승리를 거두세요",test:p=>p.stats.wins>=1},
{icon:"🌊",title:"웨이브 마스터",detail:"웨이브 5에 도달하세요",test:p=>p.stats.bestWave>=5},
{icon:"👑",title:"가디언 브레이커",detail:"네온 가디언을 격파하세요",test:p=>p.stats.bossWins>=1},
{icon:"⚡",title:"한계 돌파",detail:"한 역할을 모두 최대 강화하세요",test:p=>Object.values(p.upgrades).some(r=>r.hp+r.damage+r.speed>=15)}
];
const DIFFICULTY={easy:{label:"쉬움",speed:.82,rate:1.3,damage:.72,aim:.2,reaction:.85,teamwork:0,retreat:.22},normal:{label:"보통",speed:1,rate:1,damage:1,aim:.1,reaction:.55,teamwork:.35,retreat:.35},hard:{label:"어려움",speed:1.14,rate:.8,damage:1.18,aim:.045,reaction:.32,teamwork:.8,retreat:.48}};
const BOT_ROLES={assault:{hp:105,speed:235,range:330,near:175,rate:.34,damage:17},tank:{hp:145,speed:188,range:280,near:145,rate:.46,damage:22},sniper:{hp:85,speed:200,range:520,near:300,rate:.72,damage:34}};
function loadBestTime(){try{const value=Number(localStorage.getItem(BEST_TIME_KEY));return Number.isFinite(value)&&value>0?value:null}catch{return null}}
function saveBestTime(seconds){try{localStorage.setItem(BEST_TIME_KEY,String(seconds))}catch{}}
function formatBestTime(seconds){return seconds===null?"기록 없음":`${seconds.toFixed(1)}초`}
function loadSettings(){try{const value=JSON.parse(localStorage.getItem(SETTINGS_KEY));return{difficulty:["easy","normal","hard"].includes(value?.difficulty)?value.difficulty:"normal",shake:value?.shake!==false,sound:value?.sound!==false,vibration:value?.vibration!==false}}catch{return{difficulty:"normal",shake:true,sound:true,vibration:true}}}
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings))}catch{}}
function emptyUpgrades(){return{assault:{hp:0,damage:0,speed:0},tank:{hp:0,damage:0,speed:0},sniper:{hp:0,damage:0,speed:0}}}
function emptyStats(){return{matches:0,wins:0,kills:0,bestWave:0,bossDamage:0,bossWins:0,coinsEarned:0,damage:0,wavePlays:0}}
function loadProfile(){try{const saved=JSON.parse(localStorage.getItem(PROFILE_KEY)),upgrades=emptyUpgrades(),stats=emptyStats();for(const role of Object.keys(upgrades))for(const stat of Object.keys(upgrades[role]))upgrades[role][stat]=Math.max(0,Math.min(5,Number(saved?.upgrades?.[role]?.[stat])||0));for(const key of Object.keys(stats))stats[key]=Math.max(0,Math.floor(Number(saved?.stats?.[key])||0));return{coins:Math.max(0,Math.floor(Number(saved?.coins)||0)),upgrades,stats,claimed:saved?.claimed&&typeof saved.claimed==="object"?saved.claimed:{},challenges:saved?.challenges&&typeof saved.challenges==="object"?saved.challenges:{}}}catch{return{coins:0,upgrades:emptyUpgrades(),stats:emptyStats(),claimed:{},challenges:{}}}}
function saveProfile(){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(state.profile))}catch{}}
function periodStats(){return{matches:0,wins:0,kills:0,damage:0,wavePlays:0}}
function dayKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function weekKey(){const date=new Date(),day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);return dayKey(date)}
function ensureChallenges(){const c=state.profile.challenges||(state.profile.challenges={}),daily=dayKey(),weekly=weekKey();if(c.daily?.key!==daily)c.daily={key:daily,stats:periodStats(),claimed:{}};if(c.weekly?.key!==weekly)c.weekly={key:weekly,stats:periodStats(),claimed:{}};for(const period of [c.daily,c.weekly]){const clean=periodStats();for(const key of Object.keys(clean))clean[key]=Math.max(0,Math.floor(Number(period.stats?.[key])||0));period.stats=clean;period.claimed=period.claimed&&typeof period.claimed==="object"?period.claimed:{}}c.longLevels=c.longLevels&&typeof c.longLevels==="object"?c.longLevels:{kills:0,wins:0,boss:0};for(const key of Object.keys(LONG_MISSIONS))c.longLevels[key]=Math.max(0,Math.min(LONG_MISSIONS[key].goals.length,Math.floor(Number(c.longLevels[key])||0)));return c}
function vibrate(pattern){if(state.settings.vibration&&navigator.vibrate)navigator.vibrate(pattern)}
let audioCtx=null;
function resumeAudio(){if(!state.settings.sound)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;if(!audioCtx)audioCtx=new AudioContext();if(audioCtx.state==="suspended")audioCtx.resume()}
function tone(freq,duration=.08,volume=.045,type="square",slide=1){if(!state.settings.sound)return;resumeAudio();if(!audioCtx)return;const now=audioCtx.currentTime,osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now);osc.frequency.exponentialRampToValueAtTime(Math.max(30,freq*slide),now+duration);gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain).connect(audioCtx.destination);osc.start(now);osc.stop(now+duration)}
function sfx(name){if(!state.settings.sound)return;if(name==="shoot")tone(240,.055,.025,"square",.55);else if(name==="damage")tone(105,.12,.055,"sawtooth",.6);else if(name==="hit")tone(420,.045,.018,"triangle",1.3);else if(name==="kill"){tone(460,.12,.05,"triangle",1.8);setTimeout(()=>tone(720,.1,.035,"triangle",1.2),65)}else if(name==="ability"){tone(170,.3,.065,"sawtooth",3.2);setTimeout(()=>tone(620,.18,.04,"triangle",1.4),90)}else if(name==="wave"){tone(330,.18,.045,"triangle",1.3);setTimeout(()=>tone(440,.18,.045,"triangle",1.3),100);setTimeout(()=>tone(550,.2,.04,"triangle",1.35),200)}else if(name==="boss")tone(78,.42,.08,"sawtooth",.55);else if(name==="win"){tone(440,.2,.05,"triangle",1.25);setTimeout(()=>tone(660,.26,.05,"triangle",1.25),150)}else if(name==="lose")tone(220,.45,.055,"triangle",.45);else tone(520,.07,.03,"triangle",1.2)}
const state={running:false,paused:false,ended:false,last:0,time:120,blue:0,red:0,shake:0,selectedClass:"assault",shopClass:"assault",selectedMap:"factory",selectedMode:"classic",wave:1,waveDelay:0,waveWaiting:false,rewarded:false,bestTime:loadBestTime(),settings:loadSettings(),profile:loadProfile(),settingsFrom:"start"};let fighters=[],bullets=[],particles=[],pickups=[],pickupClock=4,matchStats={kills:0,deaths:0,shots:0,hits:0,damage:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}},d2=(a,b)=>(a.x-b.x)**2+(a.y-b.y)**2;
function skillLevel(){return matchStats.kills>=6?3:matchStats.kills>=3?2:1}
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}
function spawn(team,slot){return{x:team==="blue"?180+slot*58:WORLD.w-180-slot*58,y:WORLD.h/2+(slot-1)*155}}
function fighter(team,slot,player=false){const p=spawn(team,slot),role=["assault","tank","sniper"][slot],c=player?CLASSES[state.selectedClass]:BOT_ROLES[role],up=player?state.profile.upgrades[state.selectedClass]:{hp:0,speed:0};const maxHp=Math.round(c.hp*(1+up.hp*.06)),speed=c.speed*(1+up.speed*.03);return{...p,id:`${team}-${slot}`,team,slot,player,classType:player?state.selectedClass:role,botRole:role,r:(player?state.selectedClass:role)==="tank"?29:25,maxHp,hp:maxHp,alive:true,respawn:0,speed,vx:0,vy:0,cool:0,abilityCd:0,abilityTime:0,shield:0,ax:team==="blue"?1:-1,ay:0,strafe:Math.random()>.5?1:-1,think:Math.random(),targetId:null,stuck:0,inv:1}}
function obstacles(){return MAPS[state.selectedMap].obstacles}
function createPickup(){for(let i=0;i<24;i++){const pickup={x:620+Math.random()*560,y:170+Math.random()*760,p:Math.random()*6};if(!blocked(pickup.x,pickup.y,28))return pickup}return{x:WORLD.w/2,y:180,p:0}}
function waveEnemy(slot,wave){const f=fighter("red",slot%3),scale=1+(wave-1)*.14;f.id=`wave-${wave}-${slot}`;f.x=WORLD.w-150-(slot%2)*85;f.y=170+(slot%5)*190;f.maxHp=Math.round(f.maxHp*scale);f.hp=f.maxHp;f.speed*=1+(wave-1)*.035;f.power=1+(wave-1)*.09;return f}
function spawnWave(wave){const count=Math.min(2+wave,5),blue=fighters.filter(f=>f.team==="blue");fighters=[...blue,...Array.from({length:count},(_,i)=>waveEnemy(i,wave))];bullets=[];sfx("wave");vibrate([25,35,25])}
function makeBoss(){const f=fighter("red",1);return Object.assign(f,{id:"neon-guardian",boss:true,botRole:"tank",classType:"tank",x:WORLD.w-260,y:WORLD.h/2,r:58,maxHp:1500,hp:1500,speed:155,power:1.35,phase:1,patternCd:2.4,bossWarning:null,dashTime:0,dashHit:new Set(),spawnedPhases:{}})}
function reset(){resumeAudio();sfx("start");vibrate(18);const blue=[fighter("blue",0),fighter("blue",1,true),fighter("blue",2)];fighters=state.selectedMode==="classic"?[...blue,fighter("red",0),fighter("red",1),fighter("red",2)]:state.selectedMode==="boss"?[...blue,makeBoss()]:blue;bullets=[];particles=[];pickups=[];pickupClock=4;matchStats={kills:0,deaths:0,shots:0,hits:0,damage:0};Object.assign(state,{running:true,paused:false,ended:false,last:performance.now(),time:state.selectedMode==="wave"?180:state.selectedMode==="boss"?150:120,blue:0,red:0,shake:0,wave:1,waveDelay:0,waveWaiting:false,rewarded:false});if(state.selectedMode==="wave")spawnWave(1);[ui.start,ui.pause,ui.result].forEach(x=>x.classList.remove("visible"));hud();updateModeStatus()}
function blocked(x,y,r=24){return obstacles().some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h)}
function move(f,x,y,dt){const ox=f.x,oy=f.y,n=Math.hypot(x,y)>1?norm(x,y):{x,y};let nx=clamp(f.x+n.x*f.speed*dt,f.r,WORLD.w-f.r);if(!blocked(nx,f.y,f.r))f.x=nx;let ny=clamp(f.y+n.y*f.speed*dt,f.r,WORLD.h-f.r);if(!blocked(f.x,ny,f.r))f.y=ny;if(dt>0){f.vx=(f.x-ox)/dt;f.vy=(f.y-oy)/dt}}
function fire(f,special=false){if(!f.alive||f.cool>0)return;const c=f.player?CLASSES[f.classType]:BOT_ROLES[f.botRole],boosted=f.player&&f.abilityTime>0&&f.classType==="assault",level=f.player?skillLevel():1,piercing=special&&f.classType==="sniper",offsets=piercing&&level>=3?[-.16,0,.16]:[0],difficulty=f.team==="red"?DIFFICULTY[state.settings.difficulty]:DIFFICULTY.normal,damageBoost=f.player?1+state.profile.upgrades[f.classType].damage*.06:1;f.cool=f.player?(boosted?(level>=3?.055:.075):c.rate):c.rate*difficulty.rate*(.9+Math.random()*.2);if(f.player){matchStats.shots+=offsets.length;sfx("shoot")}for(const offset of offsets){const spread=f.player?.035:difficulty.aim,a=Math.atan2(f.ay,f.ax)+offset+(Math.random()-.5)*spread,x=Math.cos(a),y=Math.sin(a);bullets.push({x:f.x+x*32,y:f.y+y*32,vx:x*(piercing?900:660),vy:y*(piercing?900:660),team:f.team,fromPlayer:f.player,life:piercing?1.8:1.3,r:piercing?10:5,damage:(piercing?(level>=2?130:100):(f.player?c.damage:c.damage*difficulty.damage*(f.power||1)))*damageBoost,pierce:piercing?3:0,hits:[]});for(let i=0;i<(piercing?14:4);i++)particles.push({x:f.x+x*29,y:f.y+y*29,vx:x*100+(Math.random()-.5)*100,vy:y*100+(Math.random()-.5)*100,life:piercing?.5:.22,max:piercing?.5:.22,color:piercing?"#ffd45c":"#fff2a8",size:3+Math.random()*4})}}
function hit(f,b){if(!f.alive||f.inv>0)return;const reduction=f.player&&f.classType==="tank"?.82:1,damage=Math.min(f.hp,b.damage*reduction);f.hp-=damage;if(b.fromPlayer){if(!b.countedHit){matchStats.hits++;b.countedHit=true;sfx("hit")}matchStats.damage+=damage}if(state.settings.shake)state.shake=b.pierce?9:5;if(f.player){sfx("damage");vibrate(f.hp<=f.maxHp*.3?[55,25,35]:35)}for(let i=0;i<10;i++)particles.push({x:f.x,y:f.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.4,max:.4,color:f.boss?"#ffb347":COLOR[f.team],size:3+Math.random()*4});if(f.hp<=0){f.hp=0;f.alive=false;f.respawn=2.5;if(b.fromPlayer){matchStats.kills++;sfx("kill");vibrate([25,20,45])}if(f.player)matchStats.deaths++;state[b.team]++;if(state.selectedMode==="classic"&&state[b.team]>=10)finish(b.team);if(f.boss)finish("blue")}}
function bossBullet(f,x,y,speed,damage,r=7){bullets.push({x:f.x+x*65,y:f.y+y*65,vx:x*speed,vy:y*speed,team:"red",fromPlayer:false,life:2.4,r,damage,hits:[]})}
function spawnBossDrone(f,phase){if(f.spawnedPhases[phase])return;f.spawnedPhases[phase]=true;const count=phase===2?1:2;for(let i=0;i<count;i++){const drone=fighter("red",i%3);Object.assign(drone,{id:`guardian-drone-${phase}-${i}`,x:f.x-100-i*65,y:f.y+(i?90:-90),maxHp:90,hp:90,speed:215,power:1.05,r:22});fighters.push(drone)}sfx("wave")}
function startBossPattern(f){const target=me(),roll=Math.random(),type=f.phase===1?"ring":roll<(f.phase===2?.5:.34)?"ring":roll<(f.phase===2?1:.67)?"aim":"dash",warning={type,time:{easy:1.05,normal:.82,hard:.62}[state.settings.difficulty],tx:target?.x||WORLD.w/2,ty:target?.y||WORLD.h/2};f.bossWarning=warning;sfx("boss")}
function executeBossPattern(f){const w=f.bossWarning,difficulty=DIFFICULTY[state.settings.difficulty];if(!w)return;sfx("ability");vibrate([45,25,65]);state.shake=9;if(w.type==="ring"){const count=10+f.phase*4;for(let i=0;i<count;i++){const a=Math.PI*2*i/count;bossBullet(f,Math.cos(a),Math.sin(a),390+f.phase*40,12*difficulty.damage)}}else{const n=norm(w.tx-f.x,w.ty-f.y);if(w.type==="aim"){const base=Math.atan2(n.y,n.x),count=f.phase>=3?7:5;for(let i=0;i<count;i++){const a=base+(i-(count-1)/2)*.12;bossBullet(f,Math.cos(a),Math.sin(a),620,17*difficulty.damage,8)}}else{f.dashTime=.55;f.dashX=n.x;f.dashY=n.y;f.dashHit=new Set()}}f.bossWarning=null;f.patternCd=Math.max(1.2,3.3-f.phase*.55)*difficulty.rate}
function updateBoss(f,dt){const nextPhase=f.hp/f.maxHp>.66?1:f.hp/f.maxHp>.33?2:3;if(nextPhase!==f.phase){f.phase=nextPhase;spawnBossDrone(f,nextPhase);sfx("wave");vibrate([35,30,35,30,70])}if(f.dashTime>0){f.dashTime-=dt;move(f,f.dashX,f.dashY,dt*3.4);for(const target of fighters.filter(x=>x.team==="blue"&&x.alive&&!f.dashHit.has(x.id)&&d2(f,x)<(f.r+x.r+8)**2)){f.dashHit.add(target.id);hit(target,{damage:28*DIFFICULTY[state.settings.difficulty].damage,fromPlayer:false,pierce:0,team:"red"})}return}if(f.bossWarning){f.bossWarning.time-=dt;if(f.bossWarning.time<=0)executeBossPattern(f);return}f.patternCd-=dt;if(f.patternCd<=0)startBossPattern(f)}
function useAbility(){const f=me();if(!f||!f.alive||f.abilityCd>0||state.paused||state.ended)return;const level=skillLevel();f.abilityCd=10;sfx("ability");vibrate([35,25,60]);if(f.classType==="assault")f.abilityTime=level>=3?6:level>=2?5:3.5;if(f.classType==="tank"){const duration=level>=3?6:level>=2?5:3.5;f.shield=duration;f.inv=duration;if(level>=3)f.hp=Math.min(f.maxHp,f.hp+45)}if(f.classType==="sniper"){f.cool=0;fire(f,true)}for(let i=0;i<28;i++){const a=Math.random()*Math.PI*2;particles.push({x:f.x,y:f.y,vx:Math.cos(a)*(80+Math.random()*180),vy:Math.sin(a)*(80+Math.random()*180),life:.7,max:.7,color:CLASSES[f.classType].color,size:3+Math.random()*5})}}
function closest(f){let best=null,bd=Infinity;for(const o of fighters)if(o.alive&&o.team!==f.team){const d=d2(f,o);if(d<bd){bd=d;best=o}}return best}
function lineBlocked(a,b){const steps=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/38);for(let i=1;i<steps;i++){const t=i/steps;if(blocked(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,5))return true}return false}
function botTarget(f,difficulty){const enemies=fighters.filter(o=>o.alive&&o.team!==f.team);if(!enemies.length)return null;const focused=fighters.find(o=>o.id===f.targetId&&o.alive&&o.team!==f.team);if(focused&&Math.random()>.012)return focused;let best=null,bestScore=Infinity;for(const enemy of enemies){let score=d2(f,enemy);if(enemy.player)score*=1-difficulty.teamwork*.22;if(enemy.hp/enemy.maxHp<.4)score*=1-difficulty.teamwork*.28;const allies=fighters.filter(a=>a.alive&&a.team===f.team&&a!==f&&a.targetId===enemy.id).length;score*=1-allies*difficulty.teamwork*.12;if(score<bestScore){bestScore=score;best=enemy}}f.targetId=best?.id||null;return best}
function nearestPickup(f){let best=null,bd=Infinity;for(const p of pickups){const d=d2(f,p);if(d<bd){bd=d;best=p}}return best}
function playerUpdate(f,dt){let x=input.mx,y=input.my;if(keys.has("KeyW")||keys.has("ArrowUp"))y--;if(keys.has("KeyS")||keys.has("ArrowDown"))y++;if(keys.has("KeyA")||keys.has("ArrowLeft"))x--;if(keys.has("KeyD")||keys.has("ArrowRight"))x++;const baseSpeed=f.speed;if(f.classType==="assault"&&f.abilityTime>0&&skillLevel()>=3)f.speed=baseSpeed*1.25;move(f,x,y,dt);f.speed=baseSpeed;if(pointer.seen&&matchMedia("(pointer:fine)").matches){const c=camera(),n=norm(pointer.x+c.x-f.x,pointer.y+c.y-f.y);f.ax=n.x;f.ay=n.y}else if(Math.hypot(input.ax,input.ay)>.15){const n=norm(input.ax,input.ay);f.ax=n.x;f.ay=n.y}if(pointer.down||keys.has("Space")||input.fire)fire(f)}
function botUpdate(f,dt){const difficulty=f.team==="red"?DIFFICULTY[state.settings.difficulty]:DIFFICULTY.normal,role=BOT_ROLES[f.botRole],t=botTarget(f,difficulty);if(!t)return;f.think-=dt;if(f.think<=0){f.think=difficulty.reaction+Math.random()*.28;if(Math.random()<.48)f.strafe*=-1}const heal=f.hp/f.maxHp<difficulty.retreat?nearestPickup(f):null,target=heal||t,dx=target.x-f.x,dy=target.y-f.y,d=Math.hypot(dx,dy),n=norm(dx,dy);let x=0,y=0;if(heal){x=n.x;y=n.y}else{const lead=.1+difficulty.teamwork*.16,predicted={x:t.x+t.vx*lead,y:t.y+t.vy*lead},aim=norm(predicted.x-f.x,predicted.y-f.y);f.ax=aim.x;f.ay=aim.y;if(d>role.range+65){x=n.x;y=n.y}else if(d<role.near){x=-n.x;y=-n.y}x+=-n.y*f.strafe*(f.botRole==="tank"?.3:.58);y+=n.x*f.strafe*(f.botRole==="tank"?.3:.58)}const oldX=f.x,oldY=f.y,baseSpeed=f.speed;f.speed=baseSpeed*difficulty.speed;move(f,x,y,dt);if(Math.hypot(f.x-oldX,f.y-oldY)<.25&&Math.hypot(x,y)>.2){f.stuck+=dt;if(f.stuck>.18){move(f,-y*f.strafe,x*f.strafe,dt*1.6);if(f.stuck>.7){f.strafe*=-1;f.stuck=0}}}else f.stuck=0;f.speed=baseSpeed;if(!heal&&d<role.range+170&&!lineBlocked(f,t))fire(f)}
function update(dt){if(!state.running||state.paused||state.ended)return;state.time=Math.max(0,state.time-dt);state.shake=Math.max(0,state.shake-dt*25);if(state.time<=0)finish(state.selectedMode==="classic"?(state.blue===state.red?"draw":state.blue>state.red?"blue":"red"):"red");if(state.selectedMode==="wave"&&fighters.filter(f=>f.team==="red").every(f=>!f.alive)){if(state.wave>=5)finish("blue");else if(!state.waveWaiting){state.waveWaiting=true;state.waveDelay=2.2}else{state.waveDelay-=dt;if(state.waveDelay<=0){state.wave++;state.waveWaiting=false;spawnWave(state.wave)}}}pickupClock-=dt;if(pickupClock<=0&&pickups.length<3){pickups.push(createPickup());pickupClock=7+Math.random()*4}
for(const f of fighters){f.lastX=f.x;f.lastY=f.y;f.cool=Math.max(0,f.cool-dt);f.inv=Math.max(0,f.inv-dt);f.abilityCd=Math.max(0,f.abilityCd-dt);f.abilityTime=Math.max(0,f.abilityTime-dt);f.shield=Math.max(0,f.shield-dt);if(!f.alive){if(f.team==="red"&&state.selectedMode!=="classic")continue;f.respawn-=dt;if(f.respawn<=0){const p=spawn(f.team,f.slot);Object.assign(f,p,{hp:f.maxHp,alive:true,inv:1.25,targetId:null})}continue}if(f.boss){updateBoss(f,dt);if(!f.bossWarning&&f.dashTime<=0)botUpdate(f,dt)}else f.player?playerUpdate(f,dt):botUpdate(f,dt);for(let i=pickups.length-1;i>=0;i--)if(d2(f,pickups[i])<(f.r+22)**2&&f.hp<f.maxHp){f.hp=Math.min(f.maxHp,f.hp+35);pickups.splice(i,1)}}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x<0||b.y<0||b.x>WORLD.w||b.y>WORLD.h||blocked(b.x,b.y,b.r)){bullets.splice(i,1);continue}const f=fighters.find(x=>x.alive&&x.team!==b.team&&!b.hits.includes(x.id)&&d2(x,b)<(x.r+b.r)**2);if(f){b.hits.push(f.id);hit(f,b);if(b.pierce>0)b.pierce--;else bullets.splice(i,1)}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt;if(p.life<=0)particles.splice(i,1)}for(const p of pickups)p.p+=dt*4;hud()}
function me(){return fighters.find(f=>f.player)}function camera(){const p=me()||{x:WORLD.w/2,y:WORLD.h/2};return{x:clamp(p.x-innerWidth/2,0,Math.max(0,WORLD.w-innerWidth)),y:clamp(p.y-innerHeight/2,0,Math.max(0,WORLD.h-innerHeight))}}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(c){const map=MAPS[state.selectedMap];ctx.save();ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);ctx.fillStyle=map.bg;ctx.fillRect(0,0,innerWidth,innerHeight);const size=70;ctx.strokeStyle=map.grid;ctx.lineWidth=1;for(let x=-(c.x%size);x<innerWidth;x+=size){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,innerHeight);ctx.stroke()}for(let y=-(c.y%size);y<innerHeight;y+=size){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}ctx.translate(-c.x,-c.y);ctx.fillStyle="#2fd7ff0e";ctx.fillRect(0,0,330,WORLD.h);ctx.fillStyle="#ff46700e";ctx.fillRect(WORLD.w-330,0,330,WORLD.h);ctx.strokeStyle=map.edge;ctx.lineWidth=4;ctx.strokeRect(8,8,WORLD.w-16,WORLD.h-16);
for(const o of obstacles()){ctx.fillStyle=map.block;rr(o.x,o.y,o.w,o.h,18);ctx.fill();ctx.strokeStyle=map.edge;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#ffffff0d";rr(o.x+9,o.y+9,o.w-18,16,7);ctx.fill()}for(const f of fighters)if(f.boss&&f.alive&&f.bossWarning){const w=f.bossWarning,pulse=.45+.35*Math.sin(performance.now()*.025);ctx.save();ctx.strokeStyle=`rgba(255,190,70,${pulse})`;ctx.fillStyle=`rgba(255,75,105,${pulse*.18})`;ctx.lineWidth=8;ctx.setLineDash([18,12]);if(w.type==="ring"){ctx.beginPath();ctx.arc(f.x,f.y,150,0,Math.PI*2);ctx.fill();ctx.stroke()}else{ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(w.tx,w.ty);ctx.stroke();ctx.beginPath();ctx.arc(w.tx,w.ty,w.type==="dash"?65:38,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.setLineDash([]);ctx.restore()}for(const p of pickups){const r=14+Math.sin(p.p)*2;ctx.shadowColor="#54ff9b";ctx.shadowBlur=18;ctx.fillStyle="#4cf29a";ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#102f25";ctx.fillRect(p.x-3,p.y-9,6,18);ctx.fillRect(p.x-9,p.y-3,18,6)}for(const b of bullets){ctx.shadowColor=COLOR[b.team];ctx.shadowBlur=13;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
for(const f of fighters)if(f.alive){const fc=f.player?CLASSES[f.classType].color:COLOR[f.team];ctx.save();ctx.translate(f.x,f.y);ctx.rotate(Math.atan2(f.ay,f.ax));ctx.globalAlpha=f.inv>0&&f.shield<=0?.6+.3*Math.sin(performance.now()*.02):1;ctx.fillStyle=fc;ctx.shadowColor=fc;ctx.shadowBlur=f.player?24:10;ctx.fillRect(5,-7,34,14);ctx.beginPath();ctx.arc(0,0,f.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#10162a";ctx.beginPath();ctx.arc(5,0,9,0,Math.PI*2);ctx.fill();ctx.restore();ctx.globalAlpha=1;if(f.shield>0){ctx.strokeStyle="#9b8cff";ctx.lineWidth=6;ctx.shadowColor="#9b8cff";ctx.shadowBlur=20;ctx.beginPath();ctx.arc(f.x,f.y,f.r+12,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle="#0007";rr(f.x-27,f.y-42,54,7,3);ctx.fill();ctx.fillStyle=f.hp/f.maxHp>.4?"#5cf2a0":"#ffcf4e";rr(f.x-27,f.y-42,54*f.hp/f.maxHp,7,3);ctx.fill();if(f.player){ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(f.x,f.y,f.r+8,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.restore()}
function updateModeStatus(){if(!ui.modeStatus)return;ui.bossHud.classList.toggle("visible",state.running&&state.selectedMode==="boss"&&!state.ended);if(state.selectedMode==="classic")ui.modeStatus.textContent="3대3 클래식 · 먼저 10점";else if(state.selectedMode==="wave")ui.modeStatus.textContent=state.waveWaiting?`웨이브 ${state.wave} 완료 · 다음 공격 준비`:`생존 웨이브 ${state.wave}/5 · 남은 적 ${fighters.filter(f=>f.team==="red"&&f.alive).length}`;else{const boss=fighters.find(f=>f.boss);ui.modeStatus.textContent=boss?.bossWarning?`⚠ ${boss.bossWarning.type==="ring"?"원형 탄막":boss.bossWarning.type==="aim"?"조준 공격":"돌진"} 준비!`:`보스전 · 지원 로봇 ${fighters.filter(f=>f.id?.startsWith("guardian-drone")&&f.alive).length}기`;ui.bossFill.style.width=`${boss?Math.max(0,boss.hp/boss.maxHp*100):0}%`;ui.bossPhase.textContent=`PHASE ${boss?.phase||1}`} }
function hud(){ui.bs.textContent=state.blue;ui.rs.textContent=state.red;ui.mapLabel.textContent=MAPS[state.selectedMap].label;const s=Math.ceil(state.time);ui.timer.textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;const p=me();if(p){const c=CLASSES[p.classType],level=skillLevel(),needed=level===1?3-matchStats.kills:level===2?6-matchStats.kills:0;ui.classLabel.textContent=`${c.label} · HP`;ui.hp.textContent=Math.ceil(p.hp);ui.fill.style.width=`${p.hp/p.maxHp*100}%`;ui.skillProgress.textContent=level===3?"스킬 LV.3 · 최대 강화":`스킬 LV.${level} · 다음 강화까지 ${needed}킬`;ui.abilityName.textContent=`${c.ability} · LV.${level}`;ui.abilityCooldown.style.height=`${Math.min(100,p.abilityCd/10*100)}%`;ui.ability.classList.toggle("ready",p.abilityCd<=0&&p.alive);ui.ability.disabled=!p.alive;ui.respawn.textContent=p.alive?(p.abilityTime>0?`${c.ability} ${p.abilityTime.toFixed(1)}초`:p.shield>0?`보호막 ${p.shield.toFixed(1)}초`:""):`복귀까지 ${Math.max(0,p.respawn).toFixed(1)}초`}updateModeStatus()}
function finish(w){if(state.ended)return;state.ended=true;const limit=state.selectedMode==="wave"?180:state.selectedMode==="boss"?150:120,elapsed=Math.max(0,limit-state.time),isNew=state.selectedMode==="classic"&&w==="blue"&&(state.bestTime===null||elapsed<state.bestTime),accuracy=matchStats.shots?Math.round(matchStats.hits/matchStats.shots*100):0;if(isNew){state.bestTime=elapsed;saveBestTime(state.bestTime)}ui.best.textContent=formatBestTime(state.bestTime);ui.statTime.textContent=`${elapsed.toFixed(1)}초`;ui.statKills.textContent=matchStats.kills;ui.statDeaths.textContent=matchStats.deaths;ui.statShots.textContent=matchStats.shots;ui.statAccuracy.textContent=`${accuracy}%`;ui.statDamage.textContent=Math.round(matchStats.damage);ui.resultBest.textContent=state.selectedMode==="wave"?`🌊 도달 웨이브 ${state.wave}/5`:state.selectedMode==="boss"?`👑 보스에게 가한 피해 ${Math.round(matchStats.damage)}`:isNew?`🎉 최단 승리 신기록! ${formatBestTime(state.bestTime)}`:`⚡ 최단 승리 ${formatBestTime(state.bestTime)}`;ui.resultBest.classList.toggle("new-record",isNew);ui.result.classList.add("visible");ui.title.textContent=w==="draw"?"무승부":w==="blue"?(state.selectedMode==="wave"?"생존 성공!":state.selectedMode==="boss"?"보스 격파!":"BLUE 승리!"):(state.selectedMode==="classic"?"RED 승리":"도전 종료");ui.title.style.color=w==="draw"?"#fff":COLOR[w];ui.score.textContent=state.selectedMode==="classic"?`BLUE ${state.blue} : ${state.red} RED`:state.selectedMode==="wave"?`총 ${state.blue}명 처치`:`네온 가디언 도전`}
const completeMatch=finish;
function matchReward(w){if(state.rewarded)return 0;const won=w==="blue",modeBonus=state.selectedMode==="wave"?state.wave*4:state.selectedMode==="boss"&&won?35:0,reward=10+matchStats.kills*4+(won?20:0)+modeBonus,s=state.profile.stats,c=ensureChallenges(),damage=Math.round(matchStats.damage),wavePlay=state.selectedMode==="wave"?1:0;state.rewarded=true;state.profile.coins+=reward;s.matches++;s.kills+=matchStats.kills;s.damage+=damage;s.wavePlays+=wavePlay;s.coinsEarned+=reward;if(won)s.wins++;for(const period of [c.daily,c.weekly]){period.stats.matches++;period.stats.kills+=matchStats.kills;period.stats.damage+=damage;period.stats.wavePlays+=wavePlay;if(won)period.stats.wins++}if(state.selectedMode==="wave")s.bestWave=Math.max(s.bestWave,state.wave);if(state.selectedMode==="boss"){s.bossDamage+=damage;if(won)s.bossWins++}saveProfile();renderWallet();return reward}
finish=function(w){if(state.ended)return;const reward=matchReward(w);ui.resultCoins.textContent=`🪙 +${reward} 네온 코인`;sfx(w==="blue"?"win":"lose");vibrate(w==="blue"?[40,35,70,35,90]:[90,45,90]);completeMatch(w)};
function upgradeCost(level){return 40+level*35}
function renderWallet(){ui.wallet.textContent=state.profile.coins;ui.shopWallet.textContent=state.profile.coins;if(ui.missionWallet)ui.missionWallet.textContent=state.profile.coins}
function missionCard(m,value,claimed,claimKey){const progress=Math.min(value,m.goal),done=value>=m.goal;return `<article class="mission-card ${done?"complete":""}"><div class="mission-icon">${m.icon}</div><div class="mission-copy"><strong>${m.title}</strong><small>${m.detail}</small><div class="mission-progress"><i style="width:${progress/m.goal*100}%"></i></div><span>${progress.toLocaleString()} / ${m.goal.toLocaleString()}</span></div><button data-claim="${claimKey}" type="button" ${!done||claimed?"disabled":""}>${claimed?"수령 완료":`+${m.reward} 🪙`}</button></article>`}
function challengeGroup(title,note,cards,open=true){return `<details class="challenge-group" ${open?"open":""}><summary><strong>${title}</strong><small>${note}</small></summary><div class="challenge-items">${cards}</div></details>`}
function renderMissions(){const c=ensureChallenges(),starterDone=MISSIONS.every(m=>state.profile.claimed[m.id]),starter=MISSIONS.map(m=>missionCard(m,state.profile.stats[m.stat],state.profile.claimed[m.id],`beginner:${m.id}`)).join(""),daily=PERIOD_MISSIONS.daily.map(m=>missionCard(m,c.daily.stats[m.stat],c.daily.claimed[m.id],`daily:${m.id}`)).join(""),weekly=PERIOD_MISSIONS.weekly.map(m=>missionCard(m,c.weekly.stats[m.stat],c.weekly.claimed[m.id],`weekly:${m.id}`)).join(""),long=Object.entries(LONG_MISSIONS).map(([key,m])=>{const level=c.longLevels[key];if(level>=m.goals.length)return `<article class="mission-card complete"><div class="mission-icon">${m.icon}</div><div class="mission-copy"><strong>${m.title}</strong><small>모든 단계 완료</small><div class="mission-progress"><i style="width:100%"></i></div><span>최종 단계 달성</span></div><button disabled>완료</button></article>`;return missionCard({...m,detail:`${m.unit} ${m.goals[level]} · ${level+1}/${m.goals.length}단계`,goal:m.goals[level],reward:m.rewards[level]},state.profile.stats[m.stat],false,`long:${key}`)}).join("");ui.missionList.innerHTML=challengeGroup("초보자 미션",starterDone?"모두 완료 · 눌러서 보기":"한 번만 받을 수 있어요",starter,!starterDone)+challengeGroup("일일 미션","매일 새로 시작",daily)+challengeGroup("주간 미션","매주 월요일 새로 시작",weekly)+challengeGroup("장기 미션","완료하면 다음 단계 해금",long);ui.achievementList.innerHTML=ACHIEVEMENTS.map(a=>{const unlocked=a.test(state.profile);return `<article class="achievement-card ${unlocked?"unlocked":""}"><span>${unlocked?a.icon:"🔒"}</span><div><strong>${a.title}</strong><small>${a.detail}</small></div><b>${unlocked?"해금":"미달성"}</b></article>`}).join("");ui.missionList.querySelectorAll("[data-claim]").forEach(button=>button.onclick=()=>claimMission(button.dataset.claim));saveProfile();renderWallet()}
function openMissions(){ui.start.classList.remove("visible");ui.missionScreen.classList.add("visible");renderMissions()}
function closeMissions(){ui.missionScreen.classList.remove("visible");ui.start.classList.add("visible");renderWallet()}
function claimMission(claimKey){const [kind,id]=claimKey.split(":"),c=ensureChallenges();let mission,value,claimed,setClaim;if(kind==="beginner"){mission=MISSIONS.find(m=>m.id===id);value=mission&&state.profile.stats[mission.stat];claimed=state.profile.claimed[id];setClaim=()=>state.profile.claimed[id]=true}else if(kind==="daily"||kind==="weekly"){mission=PERIOD_MISSIONS[kind].find(m=>m.id===id);value=mission&&c[kind].stats[mission.stat];claimed=c[kind].claimed[id];setClaim=()=>c[kind].claimed[id]=true}else if(kind==="long"){const track=LONG_MISSIONS[id],level=c.longLevels[id];if(track&&level<track.goals.length){mission={stat:track.stat,goal:track.goals[level],reward:track.rewards[level]};value=state.profile.stats[track.stat];claimed=false;setClaim=()=>c.longLevels[id]++}}if(!mission||claimed||value<mission.goal)return;setClaim();state.profile.coins+=mission.reward;state.profile.stats.coinsEarned+=mission.reward;saveProfile();sfx("win");vibrate([25,20,50]);renderMissions()}
function renderShop(){const role=state.shopClass,levels=state.profile.upgrades[role];ui.shopClassName.textContent=`${CLASSES[role].label} 강화`;document.querySelectorAll(".shop-class-card").forEach(card=>card.classList.toggle("selected",card.dataset.class===role));document.querySelectorAll("[data-level]").forEach(el=>{const level=levels[el.dataset.level];el.textContent=`LV.${level}/5`});document.querySelectorAll("[data-upgrade]").forEach(button=>{const level=levels[button.dataset.upgrade];button.textContent=level>=5?"최대 강화":`${upgradeCost(level)} 코인`;button.disabled=level>=5});renderWallet()}
function openUpgradeShop(){ui.start.classList.remove("visible");ui.upgradeScreen.classList.add("visible");ui.shopMessage.textContent="강화 효과는 선택한 역할로 시작할 때 적용됩니다.";renderShop()}
function closeUpgradeShop(){ui.upgradeScreen.classList.remove("visible");ui.start.classList.add("visible");renderWallet()}
function buyUpgrade(stat){const level=state.profile.upgrades[state.shopClass][stat],cost=upgradeCost(level);if(level>=5)return;if(state.profile.coins<cost){ui.shopMessage.textContent=`코인이 ${cost-state.profile.coins}개 부족합니다.`;sfx("lose");return}state.profile.coins-=cost;state.profile.upgrades[state.shopClass][stat]++;saveProfile();sfx("ability");vibrate([25,20,40]);ui.shopMessage.textContent=`${CLASSES[state.shopClass].label} ${stat==="hp"?"체력":stat==="damage"?"공격력":"이동속도"} 강화 완료!`;renderShop()}
function returnToSelection(){state.running=false;state.paused=false;state.ended=false;pointer.down=false;input.fire=false;input.mx=0;input.my=0;ui.result.classList.remove("visible");ui.pause.classList.remove("visible");ui.settingsScreen.classList.remove("visible");ui.start.classList.add("visible");ui.best.textContent=formatBestTime(state.bestTime);document.querySelectorAll(".class-card").forEach(card=>card.classList.toggle("selected",card.dataset.class===state.selectedClass));document.querySelectorAll(".map-card").forEach(card=>card.classList.toggle("selected",card.dataset.map===state.selectedMap));document.querySelectorAll(".mode-card").forEach(card=>card.classList.toggle("selected",card.dataset.mode===state.selectedMode))}
function renderSettings(){document.querySelectorAll("#difficulty-options button").forEach(button=>button.classList.toggle("selected",button.dataset.value===state.settings.difficulty));ui.shakeToggle.textContent=state.settings.shake?"켜짐":"꺼짐";ui.shakeToggle.classList.toggle("selected",state.settings.shake);ui.soundToggle.textContent=state.settings.sound?"켜짐":"꺼짐";ui.soundToggle.classList.toggle("selected",state.settings.sound);ui.vibrationToggle.textContent=state.settings.vibration?"켜짐":"꺼짐";ui.vibrationToggle.classList.toggle("selected",state.settings.vibration)}
function openSettings(from){state.settingsFrom=from;ui.start.classList.remove("visible");ui.pause.classList.remove("visible");ui.settingsScreen.classList.add("visible");renderSettings()}
function closeSettings(){ui.settingsScreen.classList.remove("visible");(state.settingsFrom==="pause"?ui.pause:ui.start).classList.add("visible");if(state.settingsFrom==="pause")state.last=performance.now()}
function updateSetting(key,value){state.settings[key]=value;if(key==="shake"&&!value)state.shake=0;saveSettings();renderSettings();if(key==="sound"&&value){resumeAudio();sfx("click")}}
function pause(v){if(!state.running||state.ended)return;state.paused=v;ui.pause.classList.toggle("visible",v);if(!v)state.last=performance.now()}
function frame(now){const dt=Math.min(.033,(now-state.last)/1000||0);state.last=now;update(dt);draw(camera());requestAnimationFrame(frame)}
function stick(id,type){const el=$(id),knob=el.querySelector(".knob");let active=null;const drag=e=>{if(e.pointerId!==active)return;const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.34,d=Math.hypot(dx,dy)||1,m=Math.min(max,d),x=dx/d*m,y=dy/d*m;knob.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;if(type==="move"){input.mx=x/max;input.my=y/max}else{input.ax=x/max;input.ay=y/max;input.fire=d>12}};const end=e=>{if(e.pointerId!==active)return;active=null;knob.style.transform="translate(-50%,-50%)";if(type==="move"){input.mx=0;input.my=0}else input.fire=false};el.addEventListener("pointerdown",e=>{active=e.pointerId;el.setPointerCapture(active);drag(e)});el.addEventListener("pointermove",drag);el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end)}
addEventListener("resize",resize);
addEventListener("keydown",e=>{keys.add(e.code);if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="KeyP"&&!ui.settingsScreen.classList.contains("visible"))pause(!state.paused);if(e.code==="KeyE")useAbility()});
addEventListener("keyup",e=>keys.delete(e.code));
canvas.addEventListener("pointermove",e=>{pointer.x=e.clientX;pointer.y=e.clientY;pointer.seen=true});
canvas.addEventListener("pointerdown",e=>{if(e.button===0)pointer.down=true});
addEventListener("pointerup",()=>pointer.down=false);
canvas.addEventListener("contextmenu",e=>e.preventDefault());
document.querySelectorAll(".class-card").forEach(card=>card.onclick=()=>{document.querySelectorAll(".class-card").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");state.selectedClass=card.dataset.class});
document.querySelectorAll(".map-card").forEach(card=>card.onclick=()=>{document.querySelectorAll(".map-card").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");state.selectedMap=card.dataset.map;ui.mapLabel.textContent=MAPS[state.selectedMap].label});
document.querySelectorAll(".mode-card").forEach(card=>card.onclick=()=>{document.querySelectorAll(".mode-card").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");state.selectedMode=card.dataset.mode;updateModeStatus()});
document.querySelectorAll(".shop-class-card").forEach(card=>card.onclick=()=>{state.shopClass=card.dataset.class;ui.shopMessage.textContent="강화 효과는 선택한 역할로 시작할 때 적용됩니다.";renderShop()});
document.querySelectorAll("[data-upgrade]").forEach(button=>button.onclick=()=>buyUpgrade(button.dataset.upgrade));
document.querySelectorAll("#difficulty-options button").forEach(button=>button.onclick=()=>updateSetting("difficulty",button.dataset.value));
$("#shake-toggle").onclick=()=>updateSetting("shake",!state.settings.shake);
$("#sound-toggle").onclick=()=>updateSetting("sound",!state.settings.sound);
$("#vibration-toggle").onclick=()=>updateSetting("vibration",!state.settings.vibration);
$("#start-settings-button").onclick=()=>openSettings("start");
$("#mission-button").onclick=openMissions;
$("#mission-back-button").onclick=closeMissions;
$("#upgrade-button").onclick=openUpgradeShop;
$("#upgrade-back-button").onclick=closeUpgradeShop;
$("#pause-settings-button").onclick=()=>openSettings("pause");
$("#settings-back-button").onclick=closeSettings;
$("#ability-button").onclick=useAbility;
$("#start-button").onclick=reset;
$("#play-again-button").onclick=returnToSelection;
$("#restart-button").onclick=reset;
$("#pause-button").onclick=()=>pause(!state.paused);
$("#resume-button").onclick=()=>pause(false);
document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running&&!state.ended)pause(true)});
stick("#move-stick","move");stick("#aim-stick","aim");renderSettings();renderWallet();ui.best.textContent=formatBestTime(state.bestTime);resize();requestAnimationFrame(frame);
