"use strict";
const $=s=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d");
const ui={bs:$("#blue-score"),rs:$("#red-score"),timer:$("#timer"),hp:$("#hp-text"),fill:$("#health-fill"),respawn:$("#respawn-text"),classLabel:$("#class-label"),ability:$("#ability-button"),abilityName:$("#ability-name"),abilityCooldown:$("#ability-cooldown"),start:$("#start-screen"),pause:$("#pause-screen"),result:$("#result-screen"),title:$("#result-title"),score:$("#result-score"),best:$("#best-time"),resultBest:$("#result-best")};
const WORLD={w:1800,h:1100},COLOR={blue:"#3dd8ff",red:"#ff4d76"},keys=new Set(),pointer={x:0,y:0,down:false,seen:false},input={mx:0,my:0,ax:1,ay:0,fire:false};
const CLASSES={assault:{label:"돌격형",ability:"오버드라이브",hp:100,speed:285,rate:.19,damage:22,color:"#42d8ff"},tank:{label:"탱커형",ability:"보호막",hp:160,speed:220,rate:.34,damage:25,color:"#9b8cff"},sniper:{label:"저격형",ability:"관통탄",hp:85,speed:235,rate:.62,damage:52,color:"#ffd45c"}};
const BEST_TIME_KEY="neon-clash-best-win-time";
function loadBestTime(){try{const value=Number(localStorage.getItem(BEST_TIME_KEY));return Number.isFinite(value)&&value>0?value:null}catch{return null}}
function saveBestTime(seconds){try{localStorage.setItem(BEST_TIME_KEY,String(seconds))}catch{}}
function formatBestTime(seconds){return seconds===null?"기록 없음":`${seconds.toFixed(1)}초`}
const state={running:false,paused:false,ended:false,last:0,time:120,blue:0,red:0,shake:0,selectedClass:"assault",bestTime:loadBestTime()};let fighters=[],bullets=[],particles=[],pickups=[],pickupClock=4;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}},d2=(a,b)=>(a.x-b.x)**2+(a.y-b.y)**2;
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}
function spawn(team,slot){return{x:team==="blue"?180+slot*58:WORLD.w-180-slot*58,y:WORLD.h/2+(slot-1)*155}}
function fighter(team,slot,player=false){const p=spawn(team,slot),c=player?CLASSES[state.selectedClass]:null;return{...p,id:`${team}-${slot}`,team,slot,player,classType:player?state.selectedClass:"bot",r:player&&state.selectedClass==="tank"?29:25,maxHp:c?c.hp:100,hp:c?c.hp:100,alive:true,respawn:0,speed:c?c.speed:205,cool:0,abilityCd:0,abilityTime:0,shield:0,ax:team==="blue"?1:-1,ay:0,strafe:Math.random()>.5?1:-1,think:Math.random(),inv:1}}
function obstacles(){return[{x:500,y:200,w:115,h:265},{x:500,y:635,w:115,h:265},{x:1185,y:200,w:115,h:265},{x:1185,y:635,w:115,h:265},{x:800,y:70,w:200,h:105},{x:800,y:925,w:200,h:105},{x:820,y:435,w:160,h:230}]}
function reset(){fighters=[fighter("blue",0),fighter("blue",1,true),fighter("blue",2),fighter("red",0),fighter("red",1),fighter("red",2)];bullets=[];particles=[];pickups=[];pickupClock=4;Object.assign(state,{running:true,paused:false,ended:false,last:performance.now(),time:120,blue:0,red:0,shake:0});[ui.start,ui.pause,ui.result].forEach(x=>x.classList.remove("visible"));hud()}
function blocked(x,y,r=24){return obstacles().some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h)}
function move(f,x,y,dt){const n=Math.hypot(x,y)>1?norm(x,y):{x,y};let nx=clamp(f.x+n.x*f.speed*dt,f.r,WORLD.w-f.r);if(!blocked(nx,f.y,f.r))f.x=nx;let ny=clamp(f.y+n.y*f.speed*dt,f.r,WORLD.h-f.r);if(!blocked(f.x,ny,f.r))f.y=ny}
function fire(f,special=false){if(!f.alive||f.cool>0)return;const c=f.player?CLASSES[f.classType]:null,boosted=f.player&&f.abilityTime>0&&f.classType==="assault";f.cool=f.player?(boosted ? 0.075 : c.rate):.44+Math.random()*.1;const a=Math.atan2(f.ay,f.ax)+(Math.random()-.5)*(f.player ? 0.035 : 0.1),x=Math.cos(a),y=Math.sin(a),piercing=special&&f.classType==="sniper";bullets.push({x:f.x+x*32,y:f.y+y*32,vx:x*(piercing?900:660),vy:y*(piercing?900:660),team:f.team,life:piercing?1.8:1.3,r:piercing?10:5,damage:piercing?100:(c?c.damage:18),pierce:piercing?3:0,hits:[]});for(let i=0;i<(piercing?14:4);i++)particles.push({x:f.x+x*29,y:f.y+y*29,vx:x*100+(Math.random()-.5)*100,vy:y*100+(Math.random()-.5)*100,life:piercing ? 0.5 : 0.22,max:piercing ? 0.5 : 0.22,color:piercing?"#ffd45c":"#fff2a8",size:3+Math.random()*4})}
function hit(f,b){if(!f.alive||f.inv>0)return;const reduction=f.player&&f.classType==="tank"?.82:1;f.hp-=b.damage*reduction;state.shake=b.pierce?9:5;for(let i=0;i<10;i++)particles.push({x:f.x,y:f.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.4,max:.4,color:COLOR[f.team],size:3+Math.random()*4});if(f.hp<=0){f.hp=0;f.alive=false;f.respawn=2.5;state[b.team]++;if(state[b.team]>=10)finish(b.team)}}
function useAbility(){const f=me();if(!f||!f.alive||f.abilityCd>0||state.paused||state.ended)return;f.abilityCd=10;if(f.classType==="assault")f.abilityTime=3.5;if(f.classType==="tank"){f.shield=3.5;f.inv=3.5}if(f.classType==="sniper"){f.cool=0;fire(f,true)}for(let i=0;i<28;i++){const a=Math.random()*Math.PI*2;particles.push({x:f.x,y:f.y,vx:Math.cos(a)*(80+Math.random()*180),vy:Math.sin(a)*(80+Math.random()*180),life:.7,max:.7,color:CLASSES[f.classType].color,size:3+Math.random()*5})}}
function closest(f){let best=null,bd=Infinity;for(const o of fighters)if(o.alive&&o.team!==f.team){const d=d2(f,o);if(d<bd){bd=d;best=o}}return best}
function playerUpdate(f,dt){let x=input.mx,y=input.my;if(keys.has("KeyW")||keys.has("ArrowUp"))y--;if(keys.has("KeyS")||keys.has("ArrowDown"))y++;if(keys.has("KeyA")||keys.has("ArrowLeft"))x--;if(keys.has("KeyD")||keys.has("ArrowRight"))x++;move(f,x,y,dt);if(pointer.seen&&matchMedia("(pointer:fine)").matches){const c=camera(),n=norm(pointer.x+c.x-f.x,pointer.y+c.y-f.y);f.ax=n.x;f.ay=n.y}else if(Math.hypot(input.ax,input.ay)>.15){const n=norm(input.ax,input.ay);f.ax=n.x;f.ay=n.y}if(pointer.down||keys.has("Space")||input.fire)fire(f)}
function botUpdate(f,dt){const t=closest(f);if(!t)return;f.think-=dt;if(f.think<=0){f.think=.5+Math.random()*.7;if(Math.random()<.35)f.strafe*=-1}const dx=t.x-f.x,dy=t.y-f.y,d=Math.hypot(dx,dy),n=norm(dx,dy);f.ax=n.x;f.ay=n.y;let x=0,y=0;if(d>350){x=n.x;y=n.y}else if(d<190){x=-n.x;y=-n.y}x+=-n.y*f.strafe*.48;y+=n.x*f.strafe*.48;move(f,x,y,dt);if(d<650)fire(f)}
function update(dt){if(!state.running||state.paused||state.ended)return;state.time=Math.max(0,state.time-dt);state.shake=Math.max(0,state.shake-dt*25);if(state.time<=0)finish(state.blue===state.red?"draw":state.blue>state.red?"blue":"red");pickupClock-=dt;if(pickupClock<=0&&pickups.length<3){pickups.push({x:650+Math.random()*500,y:220+Math.random()*660,p:Math.random()*6});pickupClock=7+Math.random()*4}
for(const f of fighters){f.cool=Math.max(0,f.cool-dt);f.inv=Math.max(0,f.inv-dt);f.abilityCd=Math.max(0,f.abilityCd-dt);f.abilityTime=Math.max(0,f.abilityTime-dt);f.shield=Math.max(0,f.shield-dt);if(!f.alive){f.respawn-=dt;if(f.respawn<=0){const p=spawn(f.team,f.slot);Object.assign(f,p,{hp:f.maxHp,alive:true,inv:1.25})}continue}f.player?playerUpdate(f,dt):botUpdate(f,dt);for(let i=pickups.length-1;i>=0;i--)if(d2(f,pickups[i])<(f.r+22)**2&&f.hp<f.maxHp){f.hp=Math.min(f.maxHp,f.hp+35);pickups.splice(i,1)}}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x<0||b.y<0||b.x>WORLD.w||b.y>WORLD.h||blocked(b.x,b.y,b.r)){bullets.splice(i,1);continue}const f=fighters.find(x=>x.alive&&x.team!==b.team&&!b.hits.includes(x.id)&&d2(x,b)<(x.r+b.r)**2);if(f){b.hits.push(f.id);hit(f,b);if(b.pierce>0)b.pierce--;else bullets.splice(i,1)}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt;if(p.life<=0)particles.splice(i,1)}for(const p of pickups)p.p+=dt*4;hud()}
function me(){return fighters.find(f=>f.player)}function camera(){const p=me()||{x:WORLD.w/2,y:WORLD.h/2};return{x:clamp(p.x-innerWidth/2,0,Math.max(0,WORLD.w-innerWidth)),y:clamp(p.y-innerHeight/2,0,Math.max(0,WORLD.h-innerHeight))}}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(c){ctx.save();ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);ctx.fillStyle="#11192d";ctx.fillRect(0,0,innerWidth,innerHeight);const size=70;ctx.strokeStyle="#5a82be13";ctx.lineWidth=1;for(let x=-(c.x%size);x<innerWidth;x+=size){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,innerHeight);ctx.stroke()}for(let y=-(c.y%size);y<innerHeight;y+=size){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(innerWidth,y);ctx.stroke()}ctx.translate(-c.x,-c.y);ctx.fillStyle="#2fd7ff0e";ctx.fillRect(0,0,330,WORLD.h);ctx.fillStyle="#ff46700e";ctx.fillRect(WORLD.w-330,0,330,WORLD.h);ctx.strokeStyle="#58caff26";ctx.lineWidth=4;ctx.strokeRect(8,8,WORLD.w-16,WORLD.h-16);
for(const o of obstacles()){ctx.fillStyle="#253151";rr(o.x,o.y,o.w,o.h,18);ctx.fill();ctx.strokeStyle="#85aeff33";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#ffffff09";rr(o.x+9,o.y+9,o.w-18,16,7);ctx.fill()}for(const p of pickups){const r=14+Math.sin(p.p)*2;ctx.shadowColor="#54ff9b";ctx.shadowBlur=18;ctx.fillStyle="#4cf29a";ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#102f25";ctx.fillRect(p.x-3,p.y-9,6,18);ctx.fillRect(p.x-9,p.y-3,18,6)}for(const b of bullets){ctx.shadowColor=COLOR[b.team];ctx.shadowBlur=13;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
for(const f of fighters)if(f.alive){const fc=f.player?CLASSES[f.classType].color:COLOR[f.team];ctx.save();ctx.translate(f.x,f.y);ctx.rotate(Math.atan2(f.ay,f.ax));ctx.globalAlpha=f.inv>0&&f.shield<=0?.6+.3*Math.sin(performance.now()*.02):1;ctx.fillStyle=fc;ctx.shadowColor=fc;ctx.shadowBlur=f.player?24:10;ctx.fillRect(5,-7,34,14);ctx.beginPath();ctx.arc(0,0,f.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#10162a";ctx.beginPath();ctx.arc(5,0,9,0,Math.PI*2);ctx.fill();ctx.restore();ctx.globalAlpha=1;if(f.shield>0){ctx.strokeStyle="#9b8cff";ctx.lineWidth=6;ctx.shadowColor="#9b8cff";ctx.shadowBlur=20;ctx.beginPath();ctx.arc(f.x,f.y,f.r+12,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle="#0007";rr(f.x-27,f.y-42,54,7,3);ctx.fill();ctx.fillStyle=f.hp/f.maxHp>.4?"#5cf2a0":"#ffcf4e";rr(f.x-27,f.y-42,54*f.hp/f.maxHp,7,3);ctx.fill();if(f.player){ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(f.x,f.y,f.r+8,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.restore()}
function hud(){ui.bs.textContent=state.blue;ui.rs.textContent=state.red;const s=Math.ceil(state.time);ui.timer.textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;const p=me();if(p){const c=CLASSES[p.classType];ui.classLabel.textContent=`${c.label} · HP`;ui.hp.textContent=Math.ceil(p.hp);ui.fill.style.width=`${p.hp/p.maxHp*100}%`;ui.abilityName.textContent=c.ability;ui.abilityCooldown.style.height=`${Math.min(100,p.abilityCd/10*100)}%`;ui.ability.classList.toggle("ready",p.abilityCd<=0&&p.alive);ui.ability.disabled=!p.alive;ui.respawn.textContent=p.alive?(p.abilityTime>0?`${c.ability} ${p.abilityTime.toFixed(1)}초`:p.shield>0?`보호막 ${p.shield.toFixed(1)}초`:""):`복귀까지 ${Math.max(0,p.respawn).toFixed(1)}초`}}
function finish(w){state.ended=true;const elapsed=Math.max(0,120-state.time),isNew=w==="blue"&&(state.bestTime===null||elapsed<state.bestTime);if(isNew){state.bestTime=elapsed;saveBestTime(state.bestTime)}ui.best.textContent=formatBestTime(state.bestTime);ui.resultBest.textContent=isNew?`🎉 최단 승리 신기록! ${formatBestTime(state.bestTime)}`:`⚡ 최단 승리 ${formatBestTime(state.bestTime)}`;ui.resultBest.classList.toggle("new-record",isNew);ui.result.classList.add("visible");ui.title.textContent=w==="draw"?"무승부":w==="blue"?"BLUE 승리!":"RED 승리";ui.title.style.color=w==="draw"?"#fff":COLOR[w];ui.score.textContent=`BLUE ${state.blue} : ${state.red} RED${w==="blue"?` · ${elapsed.toFixed(1)}초`:""}`}
function returnToSelection(){state.running=false;state.paused=false;state.ended=false;pointer.down=false;input.fire=false;input.mx=0;input.my=0;ui.result.classList.remove("visible");ui.pause.classList.remove("visible");ui.start.classList.add("visible");ui.best.textContent=formatBestTime(state.bestTime);document.querySelectorAll(".class-card").forEach(card=>card.classList.toggle("selected",card.dataset.class===state.selectedClass))}
function pause(v){if(!state.running||state.ended)return;state.paused=v;ui.pause.classList.toggle("visible",v);if(!v)state.last=performance.now()}
function frame(now){const dt=Math.min(.033,(now-state.last)/1000||0);state.last=now;update(dt);draw(camera());requestAnimationFrame(frame)}
function stick(id,type){const el=$(id),knob=el.querySelector(".knob");let active=null;const drag=e=>{if(e.pointerId!==active)return;const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.34,d=Math.hypot(dx,dy)||1,m=Math.min(max,d),x=dx/d*m,y=dy/d*m;knob.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;if(type==="move"){input.mx=x/max;input.my=y/max}else{input.ax=x/max;input.ay=y/max;input.fire=d>12}};const end=e=>{if(e.pointerId!==active)return;active=null;knob.style.transform="translate(-50%,-50%)";if(type==="move"){input.mx=0;input.my=0}else input.fire=false};el.addEventListener("pointerdown",e=>{active=e.pointerId;el.setPointerCapture(active);drag(e)});el.addEventListener("pointermove",drag);el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end)}
addEventListener("resize",resize);addEventListener("keydown",e=>{keys.add(e.code);if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="KeyP")pause(!state.paused);if(e.code==="KeyE")useAbility()});addEventListener("keyup",e=>keys.delete(e.code));canvas.addEventListener("pointermove",e=>{pointer.x=e.clientX;pointer.y=e.clientY;pointer.seen=true});canvas.addEventListener("pointerdown",e=>{if(e.button===0)pointer.down=true});addEventListener("pointerup",()=>pointer.down=false);canvas.addEventListener("contextmenu",e=>e.preventDefault());document.querySelectorAll(".class-card").forEach(card=>card.onclick=()=>{document.querySelectorAll(".class-card").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");state.selectedClass=card.dataset.class});$("#ability-button").onclick=useAbility;$("#start-button").onclick=reset;$("#play-again-button").onclick=returnToSelection;$("#restart-button").onclick=reset;$("#pause-button").onclick=()=>pause(!state.paused);$("#resume-button").onclick=()=>pause(false);document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running&&!state.ended)pause(true)});stick("#move-stick","move");stick("#aim-stick","aim");ui.best.textContent=formatBestTime(state.bestTime);resize();requestAnimationFrame(frame);
