"use strict";
const $=s=>document.querySelector(s),canvas=$("#online-game"),ctx=canvas.getContext("2d"),W=1200,H=720;
const ROLES={assault:{label:"돌격형",icon:"⚡",color:"#42d8ff"},tank:{label:"탱커형",icon:"🛡️",color:"#9b8cff"},sniper:{label:"저격형",icon:"🎯",color:"#ffd45c"},support:{label:"지원형",icon:"✚",color:"#4ff0a4"}};
const MAPS={factory:{label:"네온 공장",bg:"#11192d",grid:"#5a82be22",block:"#253151",edge:"#85aeff66",obstacles:[{x:330,y:105,w:90,h:190},{x:330,y:425,w:90,h:190},{x:780,y:105,w:90,h:190},{x:780,y:425,w:90,h:190},{x:540,y:255,w:120,h:210}]},crossfire:{label:"크로스 광장",bg:"#18142b",grid:"#c278ff22",block:"#3b2851",edge:"#ef9cff66",obstacles:[{x:365,y:120,w:115,h:115},{x:720,y:120,w:115,h:115},{x:365,y:485,w:115,h:115},{x:720,y:485,w:115,h:115},{x:535,y:270,w:130,h:180},{x:165,y:300,w:75,h:120},{x:960,y:300,w:75,h:120}]},corridor:{label:"트윈 통로",bg:"#0d2024",grid:"#51ffd422",block:"#1d4748",edge:"#72ffe077",obstacles:[{x:305,y:65,w:85,h:240},{x:305,y:415,w:85,h:240},{x:560,y:150,w:80,h:420},{x:810,y:65,w:85,h:240},{x:810,y:415,w:85,h:240}]}};
const COLORS={blue:"#42d8ff",red:"#ff4d76"},PROFILE_KEY="neon-clash-profile-v1",input={x:0,y:0,ax:1,ay:0,fire:false,ability:false,auxiliary:false};
const ui={lobby:$("#online-lobby"),result:$("#online-result"),message:$("#room-result"),quick:$("#quick-match"),cancel:$("#cancel-match"),roster:$("#six-roster"),blue:$("#online-blue"),red:$("#online-red"),timer:$("#online-timer"),net:$("#network-state"),map:$("#online-map-label"),role:$("#online-role-label"),hp:$("#online-hp"),fill:$("#online-health-fill"),ability:$("#online-ability"),aux:$("#online-auxiliary"),abilityName:$("#online-ability-name"),auxName:$("#online-auxiliary-name"),title:$("#online-result-title"),score:$("#online-result-score"),feed:$("#online-kill-feed"),alert:$("#online-combat-alert")};
let socket=null,selectedRole="assault",profile=loadProfile(),playerId="",team="blue",world={players:[],bullets:[],blue:0,red:0,time:120,map:"factory"},running=false,queued=false,queueCount=0,lastSend=0,view={scale:1,ox:0,oy:0},alertTimer=0;
function loadProfile(){try{const p=JSON.parse(localStorage.getItem(PROFILE_KEY))||{};return{name:String(p.name||"플레이어").slice(0,10),skin:p.skin||"neon",badge:p.badge||"star"}}catch{return{name:"플레이어",skin:"neon",badge:"star"}}}
function serverUrl(){return String(window.NEON_CLASH_SERVER||"").trim().replace(/\/$/,"")}
function wsUrl(){return serverUrl().replace(/^http/,"ws")+"/play"}
function status(text,error=false){ui.message.textContent=text;ui.message.style.color=error?"#ff7897":"#b9c5e4";ui.net.textContent=text}
function send(value){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(value))}
function connectAndQueue(){
  if(queued)return;const url=serverUrl();if(!/^https:\/\//.test(url)){status("online-config.js에 Cloudflare 서버 주소를 먼저 입력하세요.",true);return}
  profile=loadProfile();queued=true;ui.quick.disabled=true;ui.cancel.hidden=false;status("6인 서버에 연결 중…");
  socket=new WebSocket(wsUrl());
  socket.onopen=()=>send({type:"queue",role:selectedRole,profile});
  socket.onmessage=e=>{let d;try{d=JSON.parse(e.data)}catch{return}receive(d)};
  socket.onerror=()=>status("서버에 연결하지 못했습니다. Worker 주소와 배포 상태를 확인하세요.",true);
  socket.onclose=()=>{if(running)status("서버 연결이 끊겼습니다.",true);queued=false;running=false;ui.quick.disabled=false;ui.cancel.hidden=true};
}
function cancelQueue(){send({type:"cancel"});queued=false;queueCount=0;ui.quick.disabled=false;ui.cancel.hidden=true;status("매칭을 취소했습니다.");socket?.close();socket=null;renderRoster([])}
function receive(d){
  if(d.type==="connected")playerId=d.id;
  else if(d.type==="queue"){queueCount=d.count;status(`빠른 대전 참가자 ${d.count}/${d.needed} · 6명이 모이면 시작합니다.`);renderWaiting(d.count)}
  else if(d.type==="match"){playerId=d.playerId;team=d.team;world.map=d.map;world.players=d.players;status(`매칭 완료 · ${team.toUpperCase()} 팀 · 3초 후 시작`);renderRoster(d.players)}
  else if(d.type==="start"){running=true;queued=false;ui.lobby.classList.remove("visible");ui.result.classList.remove("visible");ui.ability.disabled=false;ui.aux.disabled=false;status("6인 3대3 경기 중")}
  else if(d.type==="snapshot"){world=d.world;running=!world.ended;updateHud()}
  else if(d.type==="kill"){showKill(d);showAlert(d.team===team?`${d.killer} 처치!`:`${d.victim} 쓰러짐`,d.team===team?COLORS.blue:COLORS.red)}
  else if(d.type==="ping")showAlert(`${d.team===team?"우리 팀":"상대 팀"} · ${d.ping}`,d.team===team?COLORS.blue:COLORS.red);
  else if(d.type==="left")showAlert(`${d.name} 연결 종료`,"#ffd45c");
  else if(d.type==="end"){world=d.world;running=false;showResult(d.winner)}
}
function renderWaiting(count){ui.roster.replaceChildren(...Array.from({length:6},(_,i)=>{const el=document.createElement("div");el.innerHTML=`<b>${i<count?"✓ 참가자":"빈 자리"}</b><span>${i<3?"BLUE":"RED"}</span><em>${i<count?"준비 완료":"접속 대기"}</em>`;return el}))}
function renderRoster(players){ui.roster.replaceChildren(...players.map(p=>{const el=document.createElement("div");el.innerHTML=`<b></b><span></span><em class="ready">✓ 접속 완료</em>`;el.querySelector("b").textContent=p.name+(p.id===playerId?" (나)":"");el.querySelector("span").textContent=`${p.team.toUpperCase()} · ${ROLES[p.role]?.label||"돌격형"}`;return el}))}
function updateHud(){ui.blue.textContent=world.blue||0;ui.red.textContent=world.red||0;const t=Math.max(0,Math.ceil(world.time||0));ui.timer.textContent=`${String(Math.floor(t/60)).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`;ui.map.textContent=MAPS[world.map]?.label||"네온 공장";const me=world.players?.find(p=>p.id===playerId);if(me){ui.role.textContent=`${ROLES[me.role]?.label} · HP`;ui.hp.textContent=me.hp;ui.fill.style.width=`${Math.max(0,me.hp/me.maxHp*100)}%`}}
function showKill(d){const row=document.createElement("div");row.className="online-kill-entry";row.style.setProperty("--killer",COLORS[d.team]);row.textContent=`${d.killer} ✦ ${d.victim}`;ui.feed.prepend(row);while(ui.feed.children.length>4)ui.feed.lastChild.remove();setTimeout(()=>row.remove(),4500)}
function showAlert(text,color){clearTimeout(alertTimer);ui.alert.textContent=text;ui.alert.style.setProperty("--alert",color);ui.alert.classList.add("visible");alertTimer=setTimeout(()=>ui.alert.classList.remove("visible"),1200)}
function showResult(winner){ui.result.classList.add("visible");ui.title.textContent=winner==="draw"?"무승부":winner===team?"승리!":"패배";ui.title.style.color=winner==="draw"?"#fff":winner===team?COLORS.blue:COLORS.red;ui.score.textContent=`BLUE ${world.blue} : ${world.red} RED`;ui.ability.disabled=true;ui.aux.disabled=true}
function resize(){const d=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;canvas.width=w*d;canvas.height=h*d;view.scale=Math.min(w/W,h/H);view.ox=(w-W*view.scale)/2;view.oy=(h-H*view.scale)/2;ctx.setTransform(d,0,0,d,0,0)}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function draw(){ctx.setTransform(Math.min(devicePixelRatio||1,2),0,0,Math.min(devicePixelRatio||1,2),0,0);ctx.fillStyle="#070b16";ctx.fillRect(0,0,innerWidth,innerHeight);ctx.translate(view.ox,view.oy);ctx.scale(view.scale,view.scale);const map=MAPS[world.map]||MAPS.factory;ctx.fillStyle=map.bg;ctx.fillRect(0,0,W,H);ctx.strokeStyle=map.grid;ctx.lineWidth=1;for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle=map.edge;ctx.lineWidth=5;ctx.strokeRect(4,4,W-8,H-8);for(const o of map.obstacles){ctx.fillStyle=map.block;roundRect(o.x,o.y,o.w,o.h,18);ctx.fill();ctx.strokeStyle=map.edge;ctx.lineWidth=3;ctx.stroke()}for(const b of world.bullets||[]){ctx.shadowColor=COLORS[b.team];ctx.shadowBlur=14;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(b.x,b.y,6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}for(const p of world.players||[])drawPlayer(p);requestAnimationFrame(draw)}
function drawPlayer(p){if(!p.alive)return;const role=ROLES[p.role]||ROLES.assault,color=COLORS[p.team];ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(p.ay,p.ax));ctx.shadowColor=color;ctx.shadowBlur=p.id===playerId?24:12;ctx.fillStyle=role.color;roundRect(-19,-18,38,36,13);ctx.fill();ctx.fillStyle="#eefaff";ctx.beginPath();ctx.arc(-2,0,9,0,Math.PI*2);ctx.fill();ctx.fillRect(8,-5,45,10);ctx.restore();ctx.shadowBlur=0;ctx.strokeStyle=p.id===playerId?"#fff":color;ctx.lineWidth=p.id===playerId?5:3;ctx.beginPath();ctx.arc(p.x,p.y,38,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#050817e8";roundRect(p.x-42,p.y-62,84,20,7);ctx.fill();ctx.fillStyle=p.id===playerId?"#fff":color;ctx.font="900 12px system-ui";ctx.textAlign="center";ctx.fillText(p.name,p.x,p.y-47);ctx.fillStyle="#07111e";roundRect(p.x-30,p.y-40,60,7,4);ctx.fill();ctx.fillStyle=p.hp/p.maxHp>.4?"#5cf2a0":"#ffd45c";roundRect(p.x-30,p.y-40,60*Math.max(0,p.hp/p.maxHp),7,4);ctx.fill()}
function stick(selector,aim=false){const el=$(selector),knob=el.querySelector("i");let active=null;const move=e=>{if(e.pointerId!==active)return;const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.34,d=Math.hypot(dx,dy)||1,m=Math.min(max,d);knob.style.transform=`translate(calc(-50% + ${dx/d*m}px),calc(-50% + ${dy/d*m}px))`;const strength=Math.min(1,d/max);if(aim){input.ax=dx/d;input.ay=dy/d;input.fire=strength>.24}else{input.x=dx/d*strength;input.y=dy/d*strength}};const end=e=>{if(e.pointerId!==active)return;active=null;knob.style.transform="translate(-50%,-50%)";if(aim)input.fire=false;else{input.x=0;input.y=0}};el.onpointerdown=e=>{active=e.pointerId;el.setPointerCapture(active);move(e)};el.onpointermove=move;el.onpointerup=end;el.onpointercancel=end}
document.querySelectorAll(".online-roles button").forEach(b=>b.onclick=()=>{if(queued)return;document.querySelectorAll(".online-roles button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedRole=b.dataset.role;ui.abilityName.textContent=ROLES[selectedRole].label});
ui.quick.onclick=connectAndQueue;ui.cancel.onclick=cancelQueue;ui.ability.onclick=()=>input.ability=true;ui.aux.onclick=()=>input.auxiliary=true;$("#online-again").onclick=()=>{ui.result.classList.remove("visible");ui.lobby.classList.add("visible");queued=true;send({type:"rematch"})};
setInterval(()=>{if(running){send({type:"input",input});input.ability=false;input.auxiliary=false}},50);addEventListener("resize",resize);stick("#online-move");stick("#online-aim",true);renderWaiting(0);resize();requestAnimationFrame(draw);
