"use strict";
const $=s=>document.querySelector(s),canvas=$("#online-game"),ctx=canvas.getContext("2d"),ui={lobby:$("#online-lobby"),result:$("#online-result"),message:$("#room-result"),start:$("#online-start"),code:$("#room-code"),blue:$("#online-blue"),red:$("#online-red"),timer:$("#online-timer"),net:$("#network-state"),title:$("#online-result-title"),score:$("#online-result-score")};
const W=1200,H=720,roles={assault:{hp:100,speed:210,rate:.2,damage:20},tank:{hp:150,speed:165,rate:.35,damage:24},sniper:{hp:80,speed:175,rate:.65,damage:48}},input={x:0,y:0,ax:1,ay:0,fire:false},keys=new Set();
let peer=null,conn=null,isHost=false,selectedRole="assault",running=false,last=0,sendClock=0,roomCode="",world={fighters:[],bullets:[],blue:0,red:0,time:120,ended:false};
const obstacles=[{x:370,y:130,w:90,h:190},{x:370,y:450,w:90,h:140},{x:740,y:130,w:90,h:190},{x:740,y:450,w:90,h:140},{x:555,y:280,w:90,h:160}],clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}},blocked=(x,y,r=20)=>obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function status(text,error=false){ui.message.innerHTML=error?`<span class="red">${text}</span>`:text;ui.net.textContent=text.replace(/<[^>]+>/g,"")}
function closePeer(){try{conn?.close();peer?.destroy()}catch{}conn=null;peer=null;ui.start.disabled=true}
function peerFailed(err){status(err?.type==="peer-unavailable"?"방 코드를 찾을 수 없습니다.":"연결에 실패했습니다. 다른 네트워크에서 다시 시도해 주세요.",true);closePeer()}
function bindConnection(c){conn=c;c.on("open",()=>{status(isHost?`친구가 참가했습니다 · 방 코드 <strong>${roomCode}</strong>`:"방에 참가했습니다. 방장이 시작할 때까지 기다리세요.");if(isHost){ui.start.disabled=false;c.send({type:"hello",role:selectedRole})}else c.send({type:"hello",role:selectedRole})});c.on("data",receive);c.on("close",()=>{running=false;status("상대방과 연결이 끊어졌습니다.",true);ui.lobby.classList.add("visible")});c.on("error",peerFailed)}
function createRoom(){if(!window.Peer){status("온라인 연결 기능을 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.",true);return}closePeer();isHost=true;roomCode=code();status("방을 만드는 중…");peer=new Peer(`neon-clash-${roomCode}`);peer.on("open",()=>status(`친구에게 이 코드를 알려주세요: <strong>${roomCode}</strong>`));peer.on("connection",c=>{if(conn?.open){c.close();return}bindConnection(c)});peer.on("error",err=>{if(err.type==="unavailable-id"){roomCode=code();createRoom()}else peerFailed(err)})}
function joinRoom(){const value=ui.code.value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(value.length!==6){status("6자리 방 코드를 입력해 주세요.",true);return}if(!window.Peer){status("온라인 연결 기능을 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.",true);return}closePeer();isHost=false;roomCode=value;status("방에 연결하는 중…");peer=new Peer();peer.on("open",()=>bindConnection(peer.connect(`neon-clash-${value}`,{reliable:true})));peer.on("error",peerFailed)}
function fighter(team,slot,human=false,role=["assault","tank","sniper"][slot]){const r=roles[role];return{id:`${team}-${slot}`,team,slot,human,role,x:team==="blue"?120:W-120,y:190+slot*170,hp:r.hp,maxHp:r.hp,r:role==="tank"?27:22,speed:r.speed,cool:0,respawn:0,alive:true,ax:team==="blue"?1:-1,ay:0}}
function startHost(){if(!conn?.open)return;world={fighters:[fighter("blue",0),fighter("blue",1,true,selectedRole),fighter("blue",2),fighter("red",0),fighter("red",1,true,conn.metadata?.role||"assault"),fighter("red",2)],bullets:[],blue:0,red:0,time:120,ended:false};running=true;ui.lobby.classList.remove("visible");conn.send({type:"start",world});last=performance.now()}
function receive(data){if(!data||typeof data!=="object")return;if(data.type==="hello"&&isHost){const remote=world.fighters?.find(f=>f.team==="red"&&f.human);if(remote)remote.role=data.role;conn.metadata={role:data.role}}else if(data.type==="input"&&isHost)remoteInput=data.input;else if(data.type==="start"&&!isHost){world=data.world;running=true;ui.lobby.classList.remove("visible");last=performance.now()}else if(data.type==="snapshot"&&!isHost){world=data.world;running=!world.ended;if(world.ended)showResult(data.winner)}else if(data.type==="end")showResult(data.winner)}
let remoteInput={x:0,y:0,ax:-1,ay:0,fire:false};
function move(f,moveInput,dt){const n=Math.hypot(moveInput.x,moveInput.y)>1?norm(moveInput.x,moveInput.y):moveInput;const nx=clamp(f.x+n.x*f.speed*dt,f.r,W-f.r);if(!blocked(nx,f.y,f.r))f.x=nx;const ny=clamp(f.y+n.y*f.speed*dt,f.r,H-f.r);if(!blocked(f.x,ny,f.r))f.y=ny;if(Math.hypot(moveInput.ax,moveInput.ay)>.15){const a=norm(moveInput.ax,moveInput.ay);f.ax=a.x;f.ay=a.y}if(moveInput.fire)shoot(f)}
function shoot(f){if(!f.alive||f.cool>0)return;const role=roles[f.role];f.cool=role.rate;world.bullets.push({x:f.x+f.ax*30,y:f.y+f.ay*30,vx:f.ax*520,vy:f.ay*520,team:f.team,damage:role.damage,life:1.7,r:f.role==="sniper"?7:5})}
function bot(f,dt){const enemies=world.fighters.filter(x=>x.alive&&x.team!==f.team);if(!enemies.length)return;let t=enemies[0];for(const x of enemies)if((x.x-f.x)**2+(x.y-f.y)**2<(t.x-f.x)**2+(t.y-f.y)**2)t=x;const dx=t.x-f.x,dy=t.y-f.y,d=Math.hypot(dx,dy),n=norm(dx,dy);f.ax=n.x;f.ay=n.y;move(f,{x:d>240?n.x:d<150?-n.x:-n.y*.35,y:d>240?n.y:d<150?-n.y:n.x*.35,ax:n.x,ay:n.y,fire:d<430},dt)}
function hit(f,damage,team){f.hp-=damage;if(f.hp<=0){f.alive=false;f.respawn=2.5;world[team]++;if(world[team]>=10)endMatch(team)}}
function endMatch(winner){if(world.ended)return;world.ended=true;running=false;showResult(winner);if(conn?.open)conn.send({type:"end",winner})}
function showResult(winner){running=false;ui.result.classList.add("visible");const mine=isHost?"blue":"red";ui.title.textContent=winner==="draw"?"무승부":winner===mine?"승리!":"패배";ui.title.style.color=winner==="draw"?"#ffd45c":winner==="blue"?"#42d8ff":"#ff4d76";ui.score.textContent=`BLUE ${world.blue} : ${world.red} RED`}
function update(dt){if(!running||!isHost||world.ended)return;world.time=Math.max(0,world.time-dt);if(world.time<=0)endMatch(world.blue===world.red?"draw":world.blue>world.red?"blue":"red");for(const f of world.fighters){f.cool=Math.max(0,f.cool-dt);if(!f.alive){f.respawn-=dt;if(f.respawn<=0){f.alive=true;f.hp=f.maxHp;f.x=f.team==="blue"?120:W-120;f.y=190+f.slot*170}continue}if(f.human)move(f,f.team==="blue"?input:remoteInput,dt);else bot(f,dt)}for(let i=world.bullets.length-1;i>=0;i--){const b=world.bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||blocked(b.x,b.y,b.r)||b.x<0||b.x>W||b.y<0||b.y>H){world.bullets.splice(i,1);continue}const f=world.fighters.find(x=>x.alive&&x.team!==b.team&&(x.x-b.x)**2+(x.y-b.y)**2<(x.r+b.r)**2);if(f){hit(f,b.damage,b.team);world.bullets.splice(i,1)}}sendClock-=dt;if(sendClock<=0&&conn?.open){sendClock=.065;conn.send({type:"snapshot",world,winner:null})}}
function camera(){const team=isHost?"blue":"red",p=world.fighters.find(f=>f.team===team&&f.human)||{x:W/2,y:H/2};return{x:clamp(p.x-innerWidth/2,0,Math.max(0,W-innerWidth)),y:clamp(p.y-innerHeight/2,0,Math.max(0,H-innerHeight))}}
function draw(){const c=camera();ctx.fillStyle="#0d1427";ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(-c.x,-c.y);ctx.strokeStyle="#42d8ff12";for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle="#42d8ff0c";ctx.fillRect(0,0,250,H);ctx.fillStyle="#ff4d760c";ctx.fillRect(W-250,0,250,H);for(const o of obstacles){ctx.fillStyle="#283454";ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle="#6c8bc855";ctx.strokeRect(o.x,o.y,o.w,o.h)}for(const b of world.bullets){ctx.fillStyle=b.team==="blue"?"#8beaff":"#ff91aa";ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}for(const f of world.fighters)if(f.alive){const own=f.human&&f.team===(isHost?"blue":"red");ctx.fillStyle=f.team==="blue"?"#42d8ff":"#ff4d76";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=own?22:8;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#050816";ctx.fillRect(f.x-24,f.y-36,48,6);ctx.fillStyle="#59f3a1";ctx.fillRect(f.x-24,f.y-36,48*f.hp/f.maxHp,6);if(own){ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,f.y,f.r+7,0,Math.PI*2);ctx.stroke()}}ctx.restore();ui.blue.textContent=world.blue;ui.red.textContent=world.red;const sec=Math.ceil(world.time);ui.timer.textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
function frame(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;if(!isHost&&running&&conn?.open){sendClock-=dt;if(sendClock<=0){sendClock=.05;conn.send({type:"input",input})}}update(dt);draw();requestAnimationFrame(frame)}
function stick(selector){const el=$(selector),knob=el.querySelector("i"),aim=el.classList.contains("aim");let active=null;const drag=e=>{if(e.pointerId!==active)return;const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.34,d=Math.hypot(dx,dy)||1,m=Math.min(max,d),x=dx/d*m,y=dy/d*m;knob.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;if(aim){input.ax=x/max;input.ay=y/max;input.fire=d>12}else{input.x=x/max;input.y=y/max}};const end=e=>{if(e.pointerId!==active)return;active=null;knob.style.transform="translate(-50%,-50%)";if(aim)input.fire=false;else input.x=input.y=0};el.addEventListener("pointerdown",e=>{active=e.pointerId;el.setPointerCapture(active);drag(e)});el.addEventListener("pointermove",drag);el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end)}
document.querySelectorAll(".online-roles button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".online-roles button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedRole=b.dataset.role});$("#create-room").onclick=createRoom;$("#join-room").onclick=joinRoom;ui.start.onclick=startHost;$("#online-again").onclick=()=>location.reload();ui.code.oninput=()=>ui.code.value=ui.code.value.toUpperCase().replace(/[^A-Z0-9]/g,"");addEventListener("keydown",e=>{keys.add(e.code);if(e.code==="Space")input.fire=true});addEventListener("keyup",e=>{keys.delete(e.code);if(e.code==="Space")input.fire=false});setInterval(()=>{input.x=(keys.has("KeyD")?1:0)-(keys.has("KeyA")?1:0);input.y=(keys.has("KeyS")?1:0)-(keys.has("KeyW")?1:0)},30);addEventListener("beforeunload",closePeer);addEventListener("resize",resize);stick("#online-move");stick("#online-aim");resize();requestAnimationFrame(frame);
