"use strict";
const $=s=>document.querySelector(s),canvas=$("#online-game"),ctx=canvas.getContext("2d"),ui={lobby:$("#online-lobby"),result:$("#online-result"),message:$("#room-result"),start:$("#online-start"),copy:$("#copy-code"),code:$("#room-code"),blue:$("#online-blue"),red:$("#online-red"),timer:$("#online-timer"),net:$("#network-state"),title:$("#online-result-title"),score:$("#online-result-score"),myRole:$("#my-role"),friendRole:$("#friend-role"),myReady:$("#my-ready"),friendReady:$("#friend-ready")};
const W=1200,H=720,roles={assault:{hp:100,speed:210,rate:.2,damage:20},tank:{hp:150,speed:165,rate:.35,damage:24},sniper:{hp:80,speed:175,rate:.65,damage:48}},input={x:0,y:0,ax:1,ay:0,fire:false},keys=new Set();
let peer=null,conn=null,isHost=false,selectedRole="assault",friendRole="assault",localReady=false,remoteReady=false,running=false,last=0,sendClock=0,roomCode="",world={fighters:[],bullets:[],blue:0,red:0,time:120,ended:false};
const roleLabel={assault:"⚡ 돌격형",tank:"🛡️ 탱커형",sniper:"🎯 저격형"};
const obstacles=[{x:370,y:130,w:90,h:190},{x:370,y:450,w:90,h:140},{x:740,y:130,w:90,h:190},{x:740,y:450,w:90,h:140},{x:555,y:280,w:90,h:160}],clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}},blocked=(x,y,r=20)=>obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function status(text,error=false){ui.message.innerHTML=error?`<span class="red">${text}</span>`:text;ui.net.textContent=text.replace(/<[^>]+>/g,"")}
function updateLobby(){const connected=!!conn?.open;ui.myRole.textContent=roleLabel[selectedRole];ui.friendRole.textContent=connected?roleLabel[friendRole]:"접속 대기";ui.myReady.textContent=localReady?"✓ 준비 완료":"준비 전";ui.friendReady.textContent=remoteReady?"✓ 준비 완료":connected?"준비 전":"연결 필요";ui.myReady.classList.toggle("ready",localReady);ui.friendReady.classList.toggle("ready",remoteReady);ui.start.disabled=!connected||(localReady&&!isHost)||(isHost&&localReady&&!remoteReady);ui.start.textContent=!connected?"연결을 기다리는 중":!localReady?"준비 완료":isHost?(remoteReady?"온라인 경기 시작":"친구의 준비를 기다리는 중"):"방장이 시작할 때까지 기다리는 중"}
function resetReady(send=false){localReady=false;remoteReady=false;if(send&&conn?.open)conn.send({type:"lobby"});updateLobby()}
function closePeer(){try{conn?.close();peer?.destroy()}catch{}conn=null;peer=null;localReady=false;remoteReady=false;ui.copy.hidden=true;updateLobby()}
function peerFailed(err){status(err?.type==="peer-unavailable"?"방 코드를 찾을 수 없습니다.":"연결에 실패했습니다. 다른 네트워크에서 다시 시도해 주세요.",true);closePeer()}
function bindConnection(c){conn=c;c.on("open",()=>{resetReady();status(isHost?`친구가 참가했습니다 · 방 코드 <strong>${roomCode}</strong>`:"방에 참가했습니다. 둘 다 준비를 눌러주세요.");c.send({type:"hello",role:selectedRole});updateLobby()});c.on("data",receive);c.on("close",()=>{running=false;conn=null;resetReady();status(isHost?"친구 연결이 끊겼습니다. 같은 코드로 다시 참가할 수 있습니다.":"방장과 연결이 끊어졌습니다. 코드를 다시 입력해 주세요.",true);ui.result.classList.remove("visible");ui.lobby.classList.add("visible")});c.on("error",peerFailed)}
function createRoom(){if(!window.Peer){status("온라인 연결 기능을 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.",true);return}closePeer();isHost=true;roomCode=code();status("방을 만드는 중…");peer=new Peer(`neon-clash-${roomCode}`);peer.on("open",()=>{status(`친구에게 이 코드를 알려주세요: <strong>${roomCode}</strong>`);ui.copy.hidden=false});peer.on("connection",c=>{if(conn?.open){c.close();return}bindConnection(c)});peer.on("error",err=>{if(err.type==="unavailable-id")createRoom();else peerFailed(err)})}
function joinRoom(){const value=ui.code.value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(value.length!==6){status("6자리 방 코드를 입력해 주세요.",true);return}if(!window.Peer){status("온라인 연결 기능을 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.",true);return}closePeer();isHost=false;roomCode=value;status("방에 연결하는 중…");peer=new Peer();peer.on("open",()=>bindConnection(peer.connect(`neon-clash-${value}`,{reliable:true})));peer.on("error",peerFailed)}
function fighter(team,slot,human=false,role=["assault","tank","sniper"][slot]){const r=roles[role];return{id:`${team}-${slot}`,team,slot,human,role,x:team==="blue"?120:W-120,y:190+slot*170,hp:r.hp,maxHp:r.hp,r:role==="tank"?27:22,speed:r.speed,cool:0,respawn:0,alive:true,ax:team==="blue"?1:-1,ay:0}}
function startHost(){if(!conn?.open||!localReady||!remoteReady)return;world={fighters:[fighter("blue",0),fighter("blue",1,true,selectedRole),fighter("blue",2),fighter("red",0),fighter("red",1,true,friendRole),fighter("red",2)],bullets:[],blue:0,red:0,time:120,ended:false};running=true;ui.lobby.classList.remove("visible");conn.send({type:"start",world});last=performance.now()}
function receive(data){if(!data||typeof data!=="object")return;if(data.type==="hello"){friendRole=roles[data.role]?data.role:"assault";updateLobby()}else if(data.type==="ready"){remoteReady=!!data.ready;updateLobby()}else if(data.type==="lobby"){localReady=false;remoteReady=false;ui.result.classList.remove("visible");ui.lobby.classList.add("visible");updateLobby()}else if(data.type==="input"&&isHost)remoteInput=data.input;else if(data.type==="start"&&!isHost){world=data.world;running=true;ui.lobby.classList.remove("visible");last=performance.now()}else if(data.type==="snapshot"&&!isHost){world=data.world;running=!world.ended}else if(data.type==="end")showResult(data.winner)}
let remoteInput={x:0,y:0,ax:-1,ay:0,fire:false};
function move(f,moveInput,dt){const n=Math.hypot(moveInput.x,moveInput.y)>1?norm(moveInput.x,moveInput.y):moveInput;const nx=clamp(f.x+n.x*f.speed*dt,f.r,W-f.r);if(!blocked(nx,f.y,f.r))f.x=nx;const ny=clamp(f.y+n.y*f.speed*dt,f.r,H-f.r);if(!blocked(f.x,ny,f.r))f.y=ny;if(Math.hypot(moveInput.ax,moveInput.ay)>.15){const a=norm(moveInput.ax,moveInput.ay);f.ax=a.x;f.ay=a.y}if(moveInput.fire)shoot(f)}
function shoot(f){if(!f.alive||f.cool>0)return;const role=roles[f.role];f.cool=role.rate;world.bullets.push({x:f.x+f.ax*30,y:f.y+f.ay*30,vx:f.ax*520,vy:f.ay*520,team:f.team,damage:role.damage,life:1.7,r:f.role==="sniper"?7:5})}
function bot(f,dt){const enemies=world.fighters.filter(x=>x.alive&&x.team!==f.team);if(!enemies.length)return;let t=enemies[0];for(const x of enemies)if((x.x-f.x)**2+(x.y-f.y)**2<(t.x-f.x)**2+(t.y-f.y)**2)t=x;const dx=t.x-f.x,dy=t.y-f.y,d=Math.hypot(dx,dy),n=norm(dx,dy);f.ax=n.x;f.ay=n.y;move(f,{x:d>240?n.x:d<150?-n.x:-n.y*.35,y:d>240?n.y:d<150?-n.y:n.x*.35,ax:n.x,ay:n.y,fire:d<430},dt)}
function hit(f,damage,team){f.hp-=damage;if(f.hp<=0){f.alive=false;f.respawn=2.5;world[team]++;if(world[team]>=10)endMatch(team)}}
function endMatch(winner){if(world.ended)return;world.ended=true;running=false;showResult(winner);if(conn?.open)conn.send({type:"end",winner})}
function showResult(winner){running=false;ui.result.classList.add("visible");const mine=isHost?"blue":"red";ui.title.textContent=winner==="draw"?"무승부":winner===mine?"승리!":"패배";ui.title.style.color=winner==="draw"?"#ffd45c":winner==="blue"?"#42d8ff":"#ff4d76";ui.score.textContent=`BLUE ${world.blue} : ${world.red} RED`}
function update(dt){if(!running||!isHost||world.ended)return;world.time=Math.max(0,world.time-dt);if(world.time<=0)endMatch(world.blue===world.red?"draw":world.blue>world.red?"blue":"red");for(const f of world.fighters){f.cool=Math.max(0,f.cool-dt);if(!f.alive){f.respawn-=dt;if(f.respawn<=0){f.alive=true;f.hp=f.maxHp;f.x=f.team==="blue"?120:W-120;f.y=190+f.slot*170}continue}if(f.human)move(f,f.team==="blue"?input:remoteInput,dt);else bot(f,dt)}for(let i=world.bullets.length-1;i>=0;i--){const b=world.bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||blocked(b.x,b.y,b.r)||b.x<0||b.x>W||b.y<0||b.y>H){world.bullets.splice(i,1);continue}const f=world.fighters.find(x=>x.alive&&x.team!==b.team&&(x.x-b.x)**2+(x.y-b.y)**2<(x.r+b.r)**2);if(f){hit(f,b.damage,b.team);world.bullets.splice(i,1)}}sendClock-=dt;if(sendClock<=0&&conn?.open){sendClock=.065;conn.send({type:"snapshot",world,winner:null})}}
function camera(){const team=isHost?"blue":"red",p=world.fighters.find(f=>f.team===team&&f.human)||{x:W/2,y:H/2};return{x:clamp(p.x-innerWidth/2,0,Math.max(0,W-innerWidth)),y:clamp(p.y-innerHeight/2,0,Math.max(0,H-innerHeight))}}
function drawFighter(f){if(!f.alive)return;const localTeam=isHost?"blue":"red",own=f.human&&f.team===localTeam,friend=f.human&&!own,color=f.team==="blue"?"#42d8ff":"#ff4d76",angle=Math.atan2(f.ay,f.ax);ctx.save();ctx.translate(f.x,f.y);ctx.rotate(angle);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=own?24:friend?17:9;ctx.fillRect(5,-7,f.role==="sniper"?43:34,14);ctx.beginPath();ctx.arc(0,0,f.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#10162a";ctx.beginPath();ctx.arc(5,0,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#dff8ff";ctx.lineWidth=3;if(f.role==="tank")ctx.strokeRect(-12,-12,24,24);else if(f.role==="sniper"){ctx.beginPath();ctx.moveTo(-11,0);ctx.lineTo(11,0);ctx.moveTo(0,-11);ctx.lineTo(0,11);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(-9,8);ctx.lineTo(0,-10);ctx.lineTo(9,8);ctx.stroke()}ctx.restore();ctx.fillStyle="#050816aa";ctx.fillRect(f.x-27,f.y-43,54,7);ctx.fillStyle="#59f3a1";ctx.fillRect(f.x-27,f.y-43,54*f.hp/f.maxHp,7);if(f.human){ctx.strokeStyle=own?"#fff":"#ffd45c";ctx.lineWidth=3;ctx.setLineDash(own?[5,4]:[]);ctx.beginPath();ctx.arc(f.x,f.y,f.r+9,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}const label=own?"나":friend?"친구":`${roleLabel[f.role].split(" ")[1]} AI`;ctx.font=`900 ${f.human?16:12}px system-ui`;ctx.textAlign="center";ctx.lineWidth=4;ctx.strokeStyle="#050816";ctx.strokeText(label,f.x,f.y-53);ctx.fillStyle=own?"#fff":friend?"#ffd45c":"#aeb8d8";ctx.fillText(label,f.x,f.y-53)}
function draw(){const c=camera();ctx.fillStyle="#0d1427";ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(-c.x,-c.y);ctx.strokeStyle="#42d8ff12";for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle="#42d8ff0c";ctx.fillRect(0,0,250,H);ctx.fillStyle="#ff4d760c";ctx.fillRect(W-250,0,250,H);for(const o of obstacles){ctx.fillStyle="#283454";ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle="#6c8bc855";ctx.strokeRect(o.x,o.y,o.w,o.h)}for(const b of world.bullets){ctx.fillStyle=b.team==="blue"?"#8beaff":"#ff91aa";ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}for(const f of world.fighters)drawFighter(f);ctx.restore();ui.blue.textContent=world.blue;ui.red.textContent=world.red;const sec=Math.ceil(world.time);ui.timer.textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
function frame(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;if(!isHost&&running&&conn?.open){sendClock-=dt;if(sendClock<=0){sendClock=.05;conn.send({type:"input",input})}}update(dt);draw();requestAnimationFrame(frame)}
function stick(selector){const el=$(selector),knob=el.querySelector("i"),aim=el.classList.contains("aim");let active=null;const drag=e=>{if(e.pointerId!==active)return;const r=el.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.34,d=Math.hypot(dx,dy)||1,m=Math.min(max,d),x=dx/d*m,y=dy/d*m;knob.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;if(aim){input.ax=x/max;input.ay=y/max;input.fire=d>12}else{input.x=x/max;input.y=y/max}};const end=e=>{if(e.pointerId!==active)return;active=null;knob.style.transform="translate(-50%,-50%)";if(aim)input.fire=false;else input.x=input.y=0};el.addEventListener("pointerdown",e=>{active=e.pointerId;el.setPointerCapture(active);drag(e)});el.addEventListener("pointermove",drag);el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end)}
document.querySelectorAll(".online-roles button").forEach(b=>b.onclick=()=>{if(localReady)return;document.querySelectorAll(".online-roles button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedRole=b.dataset.role;if(conn?.open)conn.send({type:"hello",role:selectedRole});updateLobby()});$("#create-room").onclick=createRoom;$("#join-room").onclick=joinRoom;ui.start.onclick=()=>{if(!conn?.open)return;if(!localReady){localReady=true;conn.send({type:"ready",ready:true});updateLobby();return}if(isHost&&remoteReady)startHost()};ui.copy.onclick=async()=>{try{await navigator.clipboard.writeText(roomCode);ui.copy.textContent="✓ 코드가 복사됐어요";setTimeout(()=>ui.copy.textContent="방 코드 복사",1400)}catch{status(`방 코드: <strong>${roomCode}</strong>`)}};$("#online-again").onclick=()=>{ui.result.classList.remove("visible");ui.lobby.classList.add("visible");resetReady(true);status(conn?.open?"같은 방에서 다시 준비해 주세요.":"연결이 끊어졌습니다. 방을 다시 연결해 주세요.",!conn?.open)};ui.code.oninput=()=>ui.code.value=ui.code.value.toUpperCase().replace(/[^A-Z0-9]/g,"");addEventListener("keydown",e=>{keys.add(e.code);if(e.code==="Space")input.fire=true});addEventListener("keyup",e=>{keys.delete(e.code);if(e.code==="Space")input.fire=false});setInterval(()=>{input.x=(keys.has("KeyD")?1:0)-(keys.has("KeyA")?1:0);input.y=(keys.has("KeyS")?1:0)-(keys.has("KeyW")?1:0)},30);addEventListener("beforeunload",closePeer);addEventListener("resize",resize);stick("#online-move");stick("#online-aim");updateLobby();resize();requestAnimationFrame(frame);
